# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sidekiq` gem.
# Please instead update this file by running `bin/tapioca gem sidekiq`.


# Patch the ActiveJob module
#
# pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:36
module ActiveJob
  extend ::ActiveJob::EnqueueAfterTransactionCommit::ActiveJobMethods
end

class ActiveJob::Base
  include ::Sidekiq::Job::Options
  extend ::Sidekiq::Job::Options::ClassMethods

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
  def sidekiq_options_hash; end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
  def sidekiq_options_hash=(_arg0); end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
  def sidekiq_retries_exhausted_block; end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
  def sidekiq_retries_exhausted_block=(_arg0); end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
  def sidekiq_retry_in_block; end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
  def sidekiq_retry_in_block=(_arg0); end

  class << self
    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
    def sidekiq_options_hash; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
    def sidekiq_options_hash=(val); end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
    def sidekiq_retries_exhausted_block; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
    def sidekiq_retries_exhausted_block=(val); end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
    def sidekiq_retry_in_block; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
    def sidekiq_retry_in_block=(val); end

    private

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
    def __synchronized_sidekiq_options_hash; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
    def __synchronized_sidekiq_retries_exhausted_block; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:32
    def __synchronized_sidekiq_retry_in_block; end
  end
end

# pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:37
module ActiveJob::QueueAdapters; end

# pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:47
class ActiveJob::QueueAdapters::SidekiqAdapter < ::ActiveJob::QueueAdapters::AbstractAdapter
  # @api private
  #
  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:63
  def enqueue(job); end

  # Defines whether enqueuing should happen implicitly to after commit when called
  # from inside a transaction.
  # @api private
  #
  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:58
  def enqueue_after_transaction_commit?; end

  # @api private
  #
  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:82
  def enqueue_all(jobs); end

  # @api private
  #
  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:74
  def enqueue_at(job, timestamp); end

  # @api private
  #
  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:114
  def stopping?(job = T.unsafe(nil)); end
end

# Defines a class alias for backwards compatibility with enqueued Active Job jobs.
# @api private
#
# pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:118
ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper = Sidekiq::ActiveJob::Wrapper

# Sidekiq's Data API provides a Ruby object model on top
# of Sidekiq's runtime data in Redis. This API should never
# be used within application code for business logic.
#
# The Sidekiq server process never uses this API: all data
# manipulation is done directly for performance reasons to
# ensure we are using Redis as efficiently as possible at
# every callsite.
#
# This file is designed to be required within the user's
# deployment script; it should need a bare minimum of dependencies.
# Usage:
#
#   require "sidekiq/deploy"
#   Sidekiq::Deploy.mark!("Some change")
#
# If you do not pass a label, Sidekiq will try to use the latest
# git commit info.
#
# Iterable jobs are ones which provide a sequence to process using
# `build_enumerator(*args, cursor: cursor)` and then process each
# element of that sequence in `each_iteration(item, *args)`.
#
# The job is kicked off as normal:
#
#     ProcessUserSet.perform_async(123)
#
# but instead of calling `perform`, Sidekiq will call:
#
#     enum = ProcessUserSet#build_enumerator(123, cursor:nil)
#
# Your Enumerator must yield `(object, updated_cursor)` and
# Sidekiq will call your `each_iteration` method:
#
#     ProcessUserSet#each_iteration(object, 123)
#
# After every iteration, Sidekiq will check for shutdown. If we are
# stopping, the cursor will be saved to Redis and the job re-queued
# to pick up the rest of the work upon restart. Your job will get
# the updated_cursor so it can pick up right where it stopped.
#
#     enum = ProcessUserSet#build_enumerator(123, cursor: updated_cursor)
#
# The cursor object must be serializable to JSON.
#
# Note there are several APIs to help you build enumerators for
# ActiveRecord Relations, CSV files, etc. See sidekiq/job/iterable/*.rb.
# This file contains the components which track execution metrics within Sidekiq.
# SdNotify is a pure-Ruby implementation of sd_notify(3). It can be used to
# notify systemd about state changes. Methods of this package are no-op on
# non-systemd systems (eg. Darwin).
#
# The API maps closely to the original implementation of sd_notify(3),
# therefore be sure to check the official man pages prior to using SdNotify.
#
# @see https://www.freedesktop.org/software/systemd/man/sd_notify.html
#
# Sidekiq's systemd integration allows Sidekiq to inform systemd:
#  1. when it has successfully started
#  2. when it is starting shutdown
#  3. periodically for a liveness check with a watchdog thread
#
#
# Use `Sidekiq.transactional_push!` in your sidekiq.rb initializer
#
# pkg:gem/sidekiq#lib/sidekiq/version.rb:3
module Sidekiq
  class << self
    # pkg:gem/sidekiq#lib/sidekiq.rb:148
    def configure_client; end

    # Creates a Sidekiq::Config instance that is more tuned for embedding
    # within an arbitrary Ruby process. Notably it reduces concurrency by
    # default so there is less contention for CPU time with other threads.
    #
    #   instance = Sidekiq.configure_embed do |config|
    #     config.queues = %w[critical default low]
    #   end
    #   instance.run
    #   sleep 10
    #   instance.stop
    #
    # NB: it is really easy to overload a Ruby process with threads due to the GIL.
    # I do not recommend setting concurrency higher than 2-3.
    #
    # NB: Sidekiq only supports one instance in memory. You will get undefined behavior
    # if you try to embed Sidekiq twice in the same process.
    #
    # pkg:gem/sidekiq#lib/sidekiq.rb:136
    def configure_embed(&block); end

    # pkg:gem/sidekiq#lib/sidekiq.rb:109
    def configure_server(&block); end

    # pkg:gem/sidekiq#lib/sidekiq.rb:97
    def default_configuration; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:93
    def default_job_options; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:89
    def default_job_options=(hash); end

    # pkg:gem/sidekiq#lib/sidekiq.rb:65
    def dump_json(object); end

    # pkg:gem/sidekiq#lib/sidekiq.rb:73
    def ent?; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:114
    def freeze!; end

    # pkg:gem/sidekiq#lib/sidekiq/version.rb:7
    def gem_version; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:61
    def load_json(string); end

    # pkg:gem/sidekiq#lib/sidekiq.rb:105
    def loader; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:101
    def logger; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:69
    def pro?; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:81
    def redis(&block); end

    # pkg:gem/sidekiq#lib/sidekiq.rb:77
    def redis_pool; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:57
    def server?; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:85
    def strict_args!(mode = T.unsafe(nil)); end

    # pkg:gem/sidekiq#lib/sidekiq.rb:50
    def testing!(mode = T.unsafe(nil), &block); end

    # pkg:gem/sidekiq#lib/sidekiq/transaction_aware_client.rb:46
    def transactional_push!; end

    # pkg:gem/sidekiq#lib/sidekiq.rb:46
    def ❨╯°□°❩╯︵┻━┻; end
  end
end

# pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:8
module Sidekiq::ActiveJob; end

# @api private
#
# pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:10
class Sidekiq::ActiveJob::Wrapper
  include ::Sidekiq::Job
  include ::Sidekiq::Job::Options
  extend ::Sidekiq::Job::Options::ClassMethods
  extend ::Sidekiq::Job::ClassMethods

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:13
  def perform(job_data); end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
  def sidekiq_options_hash; end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
  def sidekiq_options_hash=(_arg0); end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
  def sidekiq_retries_exhausted_block; end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
  def sidekiq_retries_exhausted_block=(_arg0); end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
  def sidekiq_retry_in_block; end

  # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
  def sidekiq_retry_in_block=(_arg0); end

  class << self
    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
    def sidekiq_options_hash; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
    def sidekiq_options_hash=(val); end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
    def sidekiq_retries_exhausted_block; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
    def sidekiq_retries_exhausted_block=(val); end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
    def sidekiq_retry_in_block; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
    def sidekiq_retry_in_block=(val); end

    private

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
    def __synchronized_sidekiq_options_hash; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
    def __synchronized_sidekiq_retries_exhausted_block; end

    # pkg:gem/sidekiq#lib/active_job/queue_adapters/sidekiq_adapter.rb:11
    def __synchronized_sidekiq_retry_in_block; end
  end
end

# pkg:gem/sidekiq#lib/sidekiq/api.rb:20
module Sidekiq::ApiUtils
  # @api private
  # Calculate the latency in seconds for a job based on its enqueued timestamp
  # @param job [Hash] the job hash
  # @return [Float] latency in seconds
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:25
  def calculate_latency(job); end
end

# pkg:gem/sidekiq#lib/sidekiq/client.rb:8
class Sidekiq::Client
  include ::Sidekiq::TestingClient
  include ::Sidekiq::JobUtil

  # Sidekiq::Client is responsible for pushing job payloads to Redis.
  # Requires the :pool or :config keyword argument.
  #
  #   Sidekiq::Client.new(pool: Sidekiq::RedisConnection.create)
  #
  # Inside the Sidekiq process, you can reuse the configured resources:
  #
  #   Sidekiq::Client.new(config: config)
  #
  # @param pool [ConnectionPool] explicit Redis pool to use
  # @param config [Sidekiq::Config] use the pool and middleware from the given Sidekiq container
  # @param chain [Sidekiq::Middleware::Chain] use the given middleware chain
  #
  # pkg:gem/sidekiq#lib/sidekiq/client.rb:45
  def initialize(*args, **kwargs); end

  # Cancel the IterableJob with the given JID.
  # **NB: Cancellation is asynchronous.** Iteration checks every
  # five seconds so this will not immediately stop the given job.
  #
  # pkg:gem/sidekiq#lib/sidekiq/client.rb:64
  def cancel!(jid); end

  # Define client-side middleware:
  #
  #   client = Sidekiq::Client.new
  #   client.middleware do |chain|
  #     chain.use MyClientMiddleware
  #   end
  #   client.push('class' => 'SomeJob', 'args' => [1,2,3])
  #
  # All client instances default to the globally-defined
  # Sidekiq.client_middleware but you can change as necessary.
  #
  # pkg:gem/sidekiq#lib/sidekiq/client.rb:23
  def middleware(&block); end

  # The main method used to push a job to Redis.  Accepts a number of options:
  #
  #   queue - the named queue to use, default 'default'
  #   class - the job class to call, required
  #   args - an array of simple arguments to the perform method, must be JSON-serializable
  #   at - timestamp to schedule the job (optional), must be Numeric (e.g. Time.now.to_f)
  #   retry - whether to retry this job if it fails, default true or an integer number of retries
  #   retry_for - relative amount of time to retry this job if it fails, default nil
  #   backtrace - whether to save any error backtrace, default false
  #
  # If class is set to the class name, the jobs' options will be based on Sidekiq's default
  # job options. Otherwise, they will be based on the job class's options.
  #
  # Any options valid for a job class's sidekiq_options are also available here.
  #
  # All keys must be strings, not symbols.  NB: because we are serializing to JSON, all
  # symbols in 'args' will be converted to strings.  Note that +backtrace: true+ can take quite a bit of
  # space in Redis; a large volume of failing jobs can start Redis swapping if you aren't careful.
  #
  # Returns a unique Job ID.  If middleware stops the job, nil will be returned instead.
  #
  # Example:
  #   push('queue' => 'my_queue', 'class' => MyJob, 'args' => ['foo', 1, :bat => 'bar'])
  #
  # pkg:gem/sidekiq#lib/sidekiq/client.rb:101
  def push(item); end

  # Push a large number of jobs to Redis. This method cuts out the redis
  # network round trip latency. It pushes jobs in batches if more than
  # `:batch_size` (1000 by default) of jobs are passed. I wouldn't recommend making `:batch_size`
  # larger than 1000 but YMMV based on network quality, size of job args, etc.
  # A large number of jobs can cause a bit of Redis command processing latency.
  #
  # Accepts an `:at` option to schedule the jobs for future execution. It
  # accepts either a single Numeric timestamp (or seconds-from-now) applied
  # to every job, or an Array of Numeric values with the same size as `args`
  # to schedule each job at its corresponding time.
  #
  # Accepts an additional `:spread_interval` option (in seconds) to randomly spread
  # the jobs schedule times over the specified interval.
  #
  # Takes the same arguments as #push except that args is expected to be
  # an Array of Arrays.  All other keys are duplicated for each job.  Each job
  # is run through the client middleware pipeline and each job gets its own Job ID
  # as normal.
  #
  # Returns an array of the of pushed jobs' jids, may contain nils if any client middleware
  # prevented a job push.
  #
  # Example (pushing jobs in batches):
  #   push_bulk('class' => MyJob, 'args' => (1..100_000).to_a, batch_size: 1_000)
  #
  # pkg:gem/sidekiq#lib/sidekiq/client.rb:139
  def push_bulk(items); end

  # pkg:gem/sidekiq#lib/sidekiq/client.rb:31
  def redis_pool; end

  # pkg:gem/sidekiq#lib/sidekiq/client.rb:31
  def redis_pool=(_arg0); end

  private

  # pkg:gem/sidekiq#lib/sidekiq/client.rb:284
  def atomic_push(conn, payloads); end

  # pkg:gem/sidekiq#lib/sidekiq/client.rb:260
  def raw_push(payloads); end

  class << self
    # Resque compatibility helpers.  Note all helpers
    # should go through Sidekiq::Job#client_push.
    #
    # Example usage:
    #   Sidekiq::Client.enqueue(MyJob, 'foo', 1, :bat => 'bar')
    #
    # Messages are enqueued to the 'default' queue.
    #
    # pkg:gem/sidekiq#lib/sidekiq/client.rb:225
    def enqueue(klass, *args); end

    # Example usage:
    #   Sidekiq::Client.enqueue_in(3.minutes, MyJob, 'foo', 1, :bat => 'bar')
    #
    # pkg:gem/sidekiq#lib/sidekiq/client.rb:253
    def enqueue_in(interval, klass, *args); end

    # Example usage:
    #   Sidekiq::Client.enqueue_to(:queue_name, MyJob, 'foo', 1, :bat => 'bar')
    #
    # pkg:gem/sidekiq#lib/sidekiq/client.rb:232
    def enqueue_to(queue, klass, *args); end

    # Example usage:
    #   Sidekiq::Client.enqueue_to_in(:queue_name, 3.minutes, MyJob, 'foo', 1, :bat => 'bar')
    #
    # pkg:gem/sidekiq#lib/sidekiq/client.rb:239
    def enqueue_to_in(queue, interval, klass, *args); end

    # pkg:gem/sidekiq#lib/sidekiq/client.rb:209
    def push(item); end

    # pkg:gem/sidekiq#lib/sidekiq/client.rb:213
    def push_bulk(*, **, &); end

    # Allows sharding of jobs across any number of Redis instances.  All jobs
    # defined within the block will use the given Redis connection pool.
    #
    #   pool = ConnectionPool.new { Redis.new }
    #   Sidekiq::Client.via(pool) do
    #     SomeJob.perform_async(1,2,3)
    #     SomeOtherJob.perform_async(1,2,3)
    #   end
    #
    # Generally this is only needed for very large Sidekiq installs processing
    # thousands of jobs per second.  I do not recommend sharding unless
    # you cannot scale any other way (e.g. splitting your app into smaller apps).
    #
    # pkg:gem/sidekiq#lib/sidekiq/client.rb:199
    def via(pool); end
  end
end

# no difference for now
#
# pkg:gem/sidekiq#lib/sidekiq/middleware/modules.rb:22
Sidekiq::ClientMiddleware = Sidekiq::ServerMiddleware

# Sidekiq::Component provides a set of utility methods depending only
# on Sidekiq::Config. It assumes a config instance is available at @config.
#
# pkg:gem/sidekiq#lib/sidekiq/component.rb:24
module Sidekiq::Component
  # pkg:gem/sidekiq#lib/sidekiq/component.rb:25
  def config; end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:121
  def default_tag(dir = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:82
  def fire_event(event, options = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:78
  def handle_exception(ex, ctx = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:66
  def hostname; end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:74
  def identity; end

  # When you have a large tree of components, the `inspect` output
  # can get out of hand, especially with lots of Sidekiq::Config
  # references everywhere. We avoid calling `inspect` on more complex
  # state and use `to_s` instead to keep output manageable, #6553
  #
  # pkg:gem/sidekiq#lib/sidekiq/component.rb:103
  def inspect; end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:51
  def logger; end

  # used for time difference and relative comparisons, not persistence.
  #
  # pkg:gem/sidekiq#lib/sidekiq/component.rb:33
  def mono_ms; end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:70
  def process_nonce; end

  # This is epoch milliseconds, appropriate for persistence
  #
  # pkg:gem/sidekiq#lib/sidekiq/component.rb:28
  def real_ms; end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:55
  def redis(&block); end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:44
  def safe_thread(name, priority: T.unsafe(nil), &block); end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:59
  def tid; end

  # pkg:gem/sidekiq#lib/sidekiq/component.rb:37
  def watchdog(last_words); end
end

# Sidekiq::Config represents the global configuration for an instance of Sidekiq.
#
# pkg:gem/sidekiq#lib/sidekiq/config.rb:8
class Sidekiq::Config
  extend ::Forwardable

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:63
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:71
  def [](*, **, &); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:71
  def []=(*, **, &); end

  # How frequently Redis should be checked by a random Sidekiq process for
  # scheduled and retriable jobs. Each individual process will take turns by
  # waiting some multiple of this value.
  #
  # See sidekiq/scheduled.rb for an in-depth explanation of this value
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:251
  def average_scheduled_poll_interval=(interval); end

  # register a new queue processing subsystem
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:134
  def capsule(name); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:72
  def capsules; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:117
  def client_middleware; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:91
  def concurrency; end

  # LEGACY: edits the default capsule
  # config.concurrency = 5
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:87
  def concurrency=(val); end

  # Death handlers are called when all retries for a job have been exhausted and
  # the job dies.  It's the notification to your application
  # that this job will not succeed without manual intervention.
  #
  # Sidekiq.configure_server do |config|
  #   config.death_handlers << ->(job, ex) do
  #   end
  # end
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:242
  def death_handlers; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:129
  def default_capsule(&block); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:71
  def dig(*, **, &); end

  # Register a proc to handle any error which occurs within the Sidekiq process.
  #
  #   Sidekiq.configure_server do |config|
  #     config.error_handlers << proc {|ex,ctx_hash,config| MyErrorService.notify(ex, ctx_hash) }
  #   end
  #
  # The default error handler logs errors to @logger.
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:262
  def error_handlers; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:71
  def fetch(*, **, &); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:227
  def freeze!; end

  # INTERNAL USE ONLY
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:301
  def handle_exception(ex, ctx = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:71
  def has_key?(*, **, &); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:75
  def inspect; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:71
  def key?(*, **, &); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:157
  def local_redis_pool; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:280
  def logger; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:291
  def logger=(logger); end

  # find a singleton
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:219
  def lookup(name, default_class = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:71
  def merge!(*, **, &); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:163
  def new_redis_pool(size, name = T.unsafe(nil)); end

  # Register a block to run at a point in the Sidekiq lifecycle.
  # :startup, :quiet, :shutdown, or :exit are valid events.
  #
  #   Sidekiq.configure_server do |config|
  #     config.on(:shutdown) do
  #       puts "Goodbye cruel world!"
  #     end
  #   end
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:274
  def on(event, &block); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:113
  def queues; end

  # Edit the default capsule.
  # config.queues = %w( high default low )                 # strict
  # config.queues = %w( high,3 default,2 low,1 )           # weighted
  # config.queues = %w( feature1,1 feature2,1 feature3,1 ) # random
  #
  # With weighted priority, queue will be checked first (weight / total) of the time.
  # high will be checked first (3/6) or 50% of the time.
  # I'd recommend setting weights between 1-10. Weights in the hundreds or thousands
  # are ridiculous and unnecessarily expensive. You can get random queue ordering
  # by explicitly setting all weights to 1.
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:109
  def queues=(val); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:149
  def reap_idle_redis_connections(timeout = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:185
  def redis; end

  # All capsules must use the same Redis configuration
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:145
  def redis=(hash); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:169
  def redis_info; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:153
  def redis_pool; end

  # register global singletons which can be accessed elsewhere
  #
  # pkg:gem/sidekiq#lib/sidekiq/config.rb:208
  def register(name, instance); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:123
  def server_middleware; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:73
  def thread_priority; end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:73
  def thread_priority=(_arg0); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:81
  def to_json(*); end

  # pkg:gem/sidekiq#lib/sidekiq/config.rb:95
  def total_concurrency; end
end

# pkg:gem/sidekiq#lib/sidekiq/config.rb:11
Sidekiq::Config::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/sidekiq#lib/sidekiq/config.rb:43
Sidekiq::Config::ERROR_HANDLER = T.let(T.unsafe(nil), Proc)

# pkg:gem/sidekiq#lib/sidekiq/logger.rb:7
module Sidekiq::Context
  class << self
    # pkg:gem/sidekiq#lib/sidekiq/logger.rb:20
    def add(k, v); end

    # pkg:gem/sidekiq#lib/sidekiq/logger.rb:16
    def current; end

    # pkg:gem/sidekiq#lib/sidekiq/logger.rb:8
    def with(hash); end
  end
end

# Ruby's default thread priority is 0, which uses 100ms time slices.
# This can lead to some surprising thread starvation; if using a lot of
# CPU-heavy concurrency, it may take several seconds before a Thread gets
# on the CPU.
#
# Negative priorities lower the timeslice by half, so -1 = 50ms, -2 = 25ms, etc.
# With more frequent timeslices, we reduce the risk of unintentional timeouts
# and starvation.
#
# Customize like so:
#
#   Sidekiq.configure_server do |cfg|
#     cfg.thread_priority = 0
#   end
#
# pkg:gem/sidekiq#lib/sidekiq/component.rb:19
Sidekiq::DEFAULT_THREAD_PRIORITY = T.let(T.unsafe(nil), Integer)

# The set of dead jobs within Sidekiq. Dead jobs have failed all of
# their retries and are helding in this set pending some sort of manual
# fix. They will be removed after 6 months (dead_timeout) if not.
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:931
class Sidekiq::DeadSet < ::Sidekiq::JobSet
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:932
  def initialize; end

  # Add the given job to the Dead set.
  # @param message [String] the job data as JSON
  # @option opts [Boolean] :notify_failure (true) Whether death handlers should be called
  # @option opts [Boolean] :trim (true) Whether Sidekiq should trim the structure to keep it within configuration
  # @option opts [Exception] :ex (RuntimeError) An exception to pass to the death handlers
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:953
  def kill(message, opts = T.unsafe(nil)); end

  # Trim dead jobs which are over our storage limits
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:937
  def trim; end
end

# pkg:gem/sidekiq#lib/sidekiq/test_api.rb:80
class Sidekiq::EmptyQueueError < ::RuntimeError; end

# pkg:gem/sidekiq#lib/sidekiq/iterable_job.rb:34
module Sidekiq::IterableJob
  include ::Sidekiq::Job::Options
  include ::Sidekiq::Job
  include ::Sidekiq::Job::Iterable

  mixes_in_class_methods ::Sidekiq::Job::Options::ClassMethods
  mixes_in_class_methods ::Sidekiq::Job::ClassMethods
  mixes_in_class_methods ::Sidekiq::Job::Iterable::ClassMethods

  class << self
    # pkg:gem/sidekiq#lib/sidekiq/iterable_job.rb:35
    def included(base); end
  end
end

# Persisted iteration state from Redis for jobs using Sidekiq::IterableJob.
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:1407
class Sidekiq::IterableJobQuery
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1408
  def initialize(jids); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1412
  def [](jid); end

  private

  # Bulk-fetch iteration state for multiple JIDs in a single Redis pipeline.
  # Returns a Hash of { jid => State } for JIDs that have iteration state.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1420
  def bulk_fetch(jids); end
end

# pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
class Sidekiq::IterableJobQuery::State < ::Struct
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1460
  def cancelled; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1452
  def cursor; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1444
  def executions; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
  def jid; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
  def jid=(_); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
  def raw; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
  def raw=(_); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1448
  def runtime; end

  class << self
    # pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
    def [](*_arg0); end

    # pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
    def inspect; end

    # pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
    def keyword_init?; end

    # pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
    def members; end

    # pkg:gem/sidekiq#lib/sidekiq/api.rb:1443
    def new(*_arg0); end
  end
end

# Include this module in your job class and you can easily create
# asynchronous jobs:
#
#   class HardJob
#     include Sidekiq::Job
#     sidekiq_options queue: 'critical', retry: 5
#
#     def perform(*args)
#       # do some work
#     end
#   end
#
# Then in your Rails app, you can do this:
#
#   HardJob.perform_async(1, 2, 3)
#
# Note that perform_async is a class method, perform is an instance method.
#
# Sidekiq::Job also includes several APIs to provide compatibility with
# ActiveJob.
#
#   class SomeJob
#     include Sidekiq::Job
#     queue_as :critical
#
#     def perform(...)
#     end
#   end
#
#   SomeJob.set(wait_until: 1.hour).perform_async(123)
#
# Note that arguments passed to the job must still obey Sidekiq's
# best practice for simple, JSON-native data types. Sidekiq will not
# implement ActiveJob's more complex argument serialization. For
# this reason, we don't implement `perform_later` as our call semantics
# are very different.
#
# pkg:gem/sidekiq#lib/sidekiq/job.rb:44
module Sidekiq::Job
  include ::Sidekiq::Job::Options

  mixes_in_class_methods ::Sidekiq::Job::Options::ClassMethods
  mixes_in_class_methods ::Sidekiq::Job::ClassMethods

  # This attribute is implementation-specific and not a public API
  #
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:163
  def _context; end

  # This attribute is implementation-specific and not a public API
  #
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:163
  def _context=(_arg0); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:176
  def interrupted?; end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:160
  def jid; end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:160
  def jid=(_arg0); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:172
  def logger; end

  class << self
    # Clear all queued jobs
    #
    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:302
    def clear_all; end

    # Drain (execute) all queued jobs
    #
    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:307
    def drain_all; end

    # pkg:gem/sidekiq#lib/sidekiq/job.rb:165
    def included(base); end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:297
    def jobs; end
  end
end

# The Sidekiq testing infrastructure overrides perform_async
# so that it does not actually touch the network.  Instead it
# stores the asynchronous jobs in a per-class array so that
# their presence/absence can be asserted by your tests.
#
# This is similar to ActionMailer's :test delivery_method and its
# ActionMailer::Base.deliveries array.
#
# Example:
#
#   require 'sidekiq/testing'
#
#   assert_equal 0, HardJob.jobs.size
#   HardJob.perform_async(:something)
#   assert_equal 1, HardJob.jobs.size
#   assert_equal :something, HardJob.jobs[0]['args'][0]
#
# You can also clear and drain all job types:
#
#   Sidekiq::Job.clear_all # or .drain_all
#
# This can be useful to make sure jobs don't linger between tests:
#
#   RSpec.configure do |config|
#     config.before(:each) do
#       Sidekiq::Job.clear_all
#     end
#   end
#
# or for acceptance testing, i.e. with cucumber:
#
#   AfterStep do
#     Sidekiq::Job.drain_all
#   end
#
#   When I sign up as "foo@example.com"
#   Then I should receive a welcome email to "foo@example.com"
#
# pkg:gem/sidekiq#lib/sidekiq/job.rb:277
module Sidekiq::Job::ClassMethods
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:393
  def build_client; end

  # Clear all jobs for this worker
  #
  # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:261
  def clear; end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:378
  def client_push(item); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:278
  def delay(*args); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:282
  def delay_for(*args); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:286
  def delay_until(*args); end

  # Drain and run all jobs for this worker
  #
  # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:266
  def drain; end

  # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:291
  def execute_job(worker, args); end

  # Jobs queued for this worker
  #
  # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:256
  def jobs; end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:298
  def perform_async(*args); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:359
  def perform_at(interval, *args); end

  # Push a large number of jobs to Redis, while limiting the batch of
  # each job payload to 1,000. This method helps cut down on the number
  # of round trips to Redis, which can increase the performance of enqueueing
  # large numbers of jobs.
  #
  # +items+ must be an Array of Arrays.
  #
  # The +:at+ option schedules the jobs for future execution. It accepts
  # either a single Numeric timestamp (or seconds-from-now) applied to every
  # job, or an Array of Numeric values with the same size as +items+ to
  # schedule each job at its corresponding time.
  #
  # For finer-grained control, use `Sidekiq::Client.push_bulk` directly.
  #
  # Example (3 Redis round trips):
  #
  #     SomeJob.perform_async(1)
  #     SomeJob.perform_async(2)
  #     SomeJob.perform_async(3)
  #
  # Would instead become (1 Redis round trip):
  #
  #     SomeJob.perform_bulk([[1], [2], [3]])
  #
  # Scheduling every job 60 seconds from now (single Numeric +:at+):
  #
  #     SomeJob.perform_bulk([[1], [2], [3]], at: 60)
  #
  # Scheduling each job at its own time (Array +:at+):
  #
  #     SomeJob.perform_bulk([[1], [2]], at: [Time.now.to_f + 30, Time.now.to_f + 60])
  #
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:341
  def perform_bulk(*args, **kwargs); end

  # +interval+ must be a timestamp, numeric or something that acts
  #   numeric (like an activesupport time interval).
  #
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:347
  def perform_in(interval, *args); end

  # Inline execution of job's perform method after passing through Sidekiq.client_middleware and Sidekiq.server_middleware
  #
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:303
  def perform_inline(*args); end

  # Pop out a single job and perform it
  #
  # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:275
  def perform_one; end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:306
  def perform_sync(*args); end

  # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:282
  def process_job(job); end

  # Queue for this worker
  #
  # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:251
  def queue; end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:290
  def queue_as(q); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:294
  def set(options); end

  # Allows customization for this type of Job.
  # Legal options:
  #
  #   queue - use a named queue for this Job, default 'default'
  #   retry - enable the RetryJobs middleware for this Job, *true* to use the default
  #      or *Integer* count
  #   backtrace - whether to save any error backtrace in the retry payload to display in web UI,
  #      can be true, false or an integer number of lines to save, default *false*
  #   pool - use the given Redis connection pool to push this type of job to a given shard.
  #
  # In practice, any option is allowed.  This is the main mechanism to configure the
  # options for a specific job.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:374
  def sidekiq_options(opts = T.unsafe(nil)); end
end

# pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:7
class Sidekiq::Job::Interrupted < ::RuntimeError; end

# pkg:gem/sidekiq#lib/sidekiq/job/iterable/active_record_enumerator.rb:5
module Sidekiq::Job::Iterable
  include ::Sidekiq::Job::Iterable::Enumerators

  mixes_in_class_methods ::Sidekiq::Job::Iterable::ClassMethods

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:26
  def initialize; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:43
  def arguments; end

  # A hook to override that will be called around each iteration.
  #
  # Can be useful for some metrics collection, performance tracking etc.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:88
  def around_iteration; end

  # The enumerator to be iterated over.
  #
  # @return [Enumerator]
  #
  # @raise [NotImplementedError] with a message advising subclasses to
  #     implement an override for this method.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:121
  def build_enumerator(*); end

  # Set a flag in Redis to mark this job as cancelled.
  # Cancellation is asynchronous and is checked at the start of iteration
  # and every 5 seconds thereafter as part of the recurring state flush.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:55
  def cancel!; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:69
  def cancelled?; end

  # Access to the current object while iterating.
  # This value is not reset so the latest element is
  # explicitly available to cleanup/complete callbacks.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:41
  def current_object; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:73
  def cursor; end

  # The action to be performed on each item from the enumerator.
  #
  # @return [void]
  #
  # @raise [NotImplementedError] with a message advising subclasses to
  #     implement an override for this method.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:132
  def each_iteration(*); end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:136
  def iteration_key; end

  # A hook to override that will be called when the job is cancelled.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:106
  def on_cancel; end

  # A hook to override that will be called when the job finished iterating.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:111
  def on_complete; end

  # A hook to override that will be called when the job resumes iterating.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:94
  def on_resume; end

  # A hook to override that will be called when the job starts iterating.
  #
  # It is called only once, for the first time.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:81
  def on_start; end

  # A hook to override that will be called each time the job is interrupted.
  #
  # This can be due to interruption or sidekiq stopping.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:101
  def on_stop; end

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:141
  def perform(*args); end

  private

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:261
  def assert_enumerator!(enum); end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:298
  def cleanup; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:183
  def fetch_previous_iteration_state; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:281
  def flush_state; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:305
  def handle_completed(completed); end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:179
  def is_cancelled?; end

  # one month
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:198
  def iterate_with_enumerator(enumerator, arguments); end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:317
  def mono_now; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:254
  def reenqueue_iteration_job; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:276
  def should_interrupt?; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:244
  def verify_iteration_time(time_limit); end

  class << self
    # @api private
    #
    # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:13
    def included(base); end
  end
end

# @api private
#
# pkg:gem/sidekiq#lib/sidekiq/job/iterable/active_record_enumerator.rb:7
class Sidekiq::Job::Iterable::ActiveRecordEnumerator
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/active_record_enumerator.rb:8
  def initialize(relation, cursor: T.unsafe(nil), **options); end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/active_record_enumerator.rb:22
  def batches; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/active_record_enumerator.rb:14
  def records; end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/active_record_enumerator.rb:30
  def relations; end

  private

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/active_record_enumerator.rb:46
  def relations_size; end
end

# Three days is the longest period you generally need to wait for a retry to
# execute when using the default retry scheme. We don't want to "forget" the job
# is cancelled before it has a chance to execute and cancel itself.
#
# pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:50
Sidekiq::Job::Iterable::CANCELLATION_PERIOD = T.let(T.unsafe(nil), String)

# @api private
#
# pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:18
module Sidekiq::Job::Iterable::ClassMethods
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:19
  def method_added(method_name); end
end

# @api private
#
# pkg:gem/sidekiq#lib/sidekiq/job/iterable/csv_enumerator.rb:7
class Sidekiq::Job::Iterable::CsvEnumerator
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/csv_enumerator.rb:8
  def initialize(csv); end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/csv_enumerator.rb:23
  def batches(cursor:, batch_size: T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/csv_enumerator.rb:16
  def rows(cursor:); end

  private

  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/csv_enumerator.rb:33
  def count_of_rows_in_file; end
end

# pkg:gem/sidekiq#lib/sidekiq/job/iterable/enumerators.rb:9
module Sidekiq::Job::Iterable::Enumerators
  # Builds Enumerator from `ActiveRecord::Relation` and enumerates on batches of records.
  # Each Enumerator tick moves the cursor `:batch_size` rows forward.
  # @see #active_record_records_enumerator
  #
  # @example
  #   def build_enumerator(product_id, cursor:)
  #     active_record_batches_enumerator(
  #       Comment.where(product_id: product_id).select(:id),
  #       cursor: cursor,
  #       batch_size: 100
  #     )
  #   end
  #
  #   def each_iteration(batch_of_comments, product_id)
  #     comment_ids = batch_of_comments.map(&:id)
  #     CommentService.call(comment_ids: comment_ids)
  #   end
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/enumerators.rb:68
  def active_record_batches_enumerator(relation, cursor:, **options); end

  # Builds Enumerator from `ActiveRecord::Relation`.
  # Each Enumerator tick moves the cursor one row forward.
  #
  # @param relation [ActiveRecord::Relation] relation to iterate
  # @param cursor [Object] offset id to start iteration from
  # @param options [Hash] additional options that will be passed to relevant
  #   ActiveRecord batching methods
  #
  # @return [ActiveRecordEnumerator]
  #
  # @example
  #   def build_enumerator(cursor:)
  #     active_record_records_enumerator(User.all, cursor: cursor)
  #   end
  #
  #   def each_iteration(user)
  #     user.notify_about_something
  #   end
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/enumerators.rb:46
  def active_record_records_enumerator(relation, cursor:, **options); end

  # Builds Enumerator from `ActiveRecord::Relation` and enumerates on batches,
  # yielding `ActiveRecord::Relation`s.
  # @see #active_record_records_enumerator
  #
  # @example
  #   def build_enumerator(product_id, cursor:)
  #     active_record_relations_enumerator(
  #       Product.find(product_id).comments,
  #       cursor: cursor,
  #       batch_size: 100,
  #     )
  #   end
  #
  #   def each_iteration(batch_of_comments, product_id)
  #     # batch_of_comments will be a Comment::ActiveRecord_Relation
  #     batch_of_comments.update_all(deleted: true)
  #   end
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/enumerators.rb:90
  def active_record_relations_enumerator(relation, cursor:, **options); end

  # Builds Enumerator object from a given array, using +cursor+ as an offset.
  #
  # @param array [Array]
  # @param cursor [Integer] offset to start iteration from
  #
  # @return [Enumerator]
  #
  # @example
  #   array_enumerator(['build', 'enumerator', 'from', 'any', 'array'], cursor: cursor)
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/enumerators.rb:20
  def array_enumerator(array, cursor:); end

  # Builds Enumerator from a CSV file and enumerates on batches of records.
  #
  # @param csv [CSV] an instance of CSV object
  # @param cursor [Integer] offset to start iteration from
  # @option options :batch_size [Integer] (100) size of the batch
  #
  # @example
  #   def build_enumerator(import_id, cursor:)
  #     import = Import.find(import_id)
  #     csv_batches_enumerator(import.csv, cursor: cursor)
  #   end
  #
  #   def each_iteration(batch_of_csv_rows)
  #     # ...
  #   end
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/enumerators.rb:129
  def csv_batches_enumerator(csv, cursor:, **options); end

  # Builds Enumerator from a CSV file.
  #
  # @param csv [CSV] an instance of CSV object
  # @param cursor [Integer] offset to start iteration from
  #
  # @example
  #   def build_enumerator(import_id, cursor:)
  #     import = Import.find(import_id)
  #     csv_enumerator(import.csv, cursor: cursor)
  #   end
  #
  #   def each_iteration(csv_row)
  #     # insert csv_row into database
  #   end
  #
  # pkg:gem/sidekiq#lib/sidekiq/job/iterable/enumerators.rb:109
  def csv_enumerator(csv, cursor:); end
end

# pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:193
Sidekiq::Job::Iterable::STATE_FLUSH_INTERVAL = T.let(T.unsafe(nil), Integer)

# seconds
# we need to keep the state around as long as the job
# might be retrying
#
# pkg:gem/sidekiq#lib/sidekiq/job/iterable.rb:196
Sidekiq::Job::Iterable::STATE_TTL = T.let(T.unsafe(nil), Integer)

# The Options module is extracted so we can include it in ActiveJob::Base
# and allow native AJs to configure Sidekiq features/internals.
#
# pkg:gem/sidekiq#lib/sidekiq/job.rb:48
module Sidekiq::Job::Options
  mixes_in_class_methods ::Sidekiq::Job::Options::ClassMethods

  class << self
    # pkg:gem/sidekiq#lib/sidekiq/job.rb:49
    def included(base); end
  end
end

# pkg:gem/sidekiq#lib/sidekiq/job.rb:56
module Sidekiq::Job::Options::ClassMethods
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:88
  def get_sidekiq_options; end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:92
  def sidekiq_class_attribute(*attrs); end

  # Allows customization for this type of Job.
  # Legal options:
  #
  #   queue - name of queue to use for this job type, default *default*
  #   retry - enable retries for this Job in case of error during execution,
  #      *true* to use the default or *Integer* count
  #   backtrace - whether to save any error backtrace in the retry payload to display in web UI,
  #      can be true, false or an integer number of lines to save, default *false*
  #
  # In practice, any option is allowed.  This is the main mechanism to configure the
  # options for a specific job.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:71
  def sidekiq_options(opts = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:84
  def sidekiq_retries_exhausted(&block); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:80
  def sidekiq_retry_in(&block); end
end

# pkg:gem/sidekiq#lib/sidekiq/job.rb:57
Sidekiq::Job::Options::ClassMethods::ACCESSOR_MUTEX = T.let(T.unsafe(nil), Thread::Mutex)

# This helper class encapsulates the set options for `set`, e.g.
#
#     SomeJob.set(queue: 'foo').perform_async(....)
#
# pkg:gem/sidekiq#lib/sidekiq/job.rb:184
class Sidekiq::Job::Setter
  include ::Sidekiq::JobUtil

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:187
  def initialize(klass, opts); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:205
  def perform_async(*args); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:263
  def perform_at(interval, *args); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:253
  def perform_bulk(args, **options); end

  # +interval+ must be a timestamp, numeric or something that acts
  #   numeric (like an activesupport time interval).
  #
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:260
  def perform_in(interval, *args); end

  # Explicit inline execution of a job. Returns nil if the job did not
  # execute, true otherwise.
  #
  # pkg:gem/sidekiq#lib/sidekiq/job.rb:215
  def perform_inline(*args); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:251
  def perform_sync(*args); end

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:197
  def set(options); end

  private

  # pkg:gem/sidekiq#lib/sidekiq/job.rb:267
  def at(interval); end
end

# Represents a pending job within a Sidekiq queue.
#
# The job should be considered immutable but may be
# removed from the queue via JobRecord#delete.
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:393
class Sidekiq::JobRecord
  include ::Sidekiq::ApiUtils

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:408
  def initialize(item, queue_name = T.unsafe(nil)); end

  # Access arbitrary attributes within the job hash
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:538
  def [](name); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:473
  def args; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:485
  def bid; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:507
  def created_at; end

  # Remove this job from the queue
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:530
  def delete; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:451
  def display_args; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:434
  def display_class; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:501
  def enqueued_at; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:515
  def error_backtrace; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:489
  def failed_at; end

  # the parsed Hash of job data
  # @!attribute [r] Item
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:398
  def item; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:481
  def iterable_state; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:477
  def jid; end

  # This is the job class which Sidekiq will execute. If using ActiveJob,
  # this class will be the ActiveJob adapter class rather than a specific job.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:430
  def klass; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:525
  def latency; end

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:417
  def parse(item); end

  # the queue associated with this job
  # @!attribute [r] Queue
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:404
  def queue; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:495
  def retried_at; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:511
  def tags; end

  # the underlying String in Redis
  # @!attribute [r] Value
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:401
  def value; end

  private

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:550
  def deserialize_argument(argument); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:566
  def serialized_global_id?(hash); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:576
  def time_from_timestamp(timestamp); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:570
  def uncompress_backtrace(backtrace); end
end

# pkg:gem/sidekiq#lib/sidekiq/api.rb:547
Sidekiq::JobRecord::ACTIVE_JOB_PREFIX = T.let(T.unsafe(nil), String)

# pkg:gem/sidekiq#lib/sidekiq/api.rb:548
Sidekiq::JobRecord::GLOBALID_KEY = T.let(T.unsafe(nil), String)

# Base class for all sorted sets which contain jobs, e.g. scheduled, retry and dead.
# Sidekiq Pro and Enterprise add additional sorted sets which do not contain job data,
# e.g. Batches.
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:726
class Sidekiq::JobSet < ::Sidekiq::SortedSet
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:903
  def delete(score, jid); end

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:887
  def delete_by_jid(score, jid); end

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:877
  def delete_by_value(name, value); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:771
  def each; end

  # Fetch jobs that match a given time or Range. Job ID is an
  # optional second argument.
  #
  # @param score [Time,Range] a specific timestamp or range
  # @param jid [String, optional] find a specific JID within the score
  # @return [Array<SortedEntry>] any results found, can be empty
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:799
  def fetch(score, jid = T.unsafe(nil)); end

  # Find the job with the given JID within this sorted set.
  # *This is a slow O(n) operation*.  Do not use for app logic.
  #
  # @param jid [String] the job identifier
  # @return [SortedEntry] the record or nil
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:824
  def find_job(jid); end

  # Move all jobs from this Set to the Dead Set.
  # See DeadSet#kill
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:758
  def kill_all(notify_failure: T.unsafe(nil), ex: T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:736
  def pop_each; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:835
  def remove_job(entry); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:746
  def retry_all; end

  # Add a job with the associated timestamp to this set.
  # @param timestamp [Time] the score for the job
  # @param job [Hash] the job data
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:730
  def schedule(timestamp, job); end
end

# pkg:gem/sidekiq#lib/sidekiq/job_util.rb:7
module Sidekiq::JobUtil
  # pkg:gem/sidekiq#lib/sidekiq/job_util.rb:43
  def normalize_item(item); end

  # pkg:gem/sidekiq#lib/sidekiq/job_util.rb:69
  def normalized_hash(item_class); end

  # pkg:gem/sidekiq#lib/sidekiq/job_util.rb:65
  def now_in_millis; end

  # pkg:gem/sidekiq#lib/sidekiq/job_util.rb:12
  def validate(item); end

  # pkg:gem/sidekiq#lib/sidekiq/job_util.rb:21
  def verify_json(item); end

  private

  # pkg:gem/sidekiq#lib/sidekiq/job_util.rb:109
  def json_unsafe?(item); end
end

# pkg:gem/sidekiq#lib/sidekiq/job_util.rb:80
Sidekiq::JobUtil::RECURSIVE_JSON_UNSAFE = T.let(T.unsafe(nil), Hash)

# These functions encapsulate various job utilities.
#
# pkg:gem/sidekiq#lib/sidekiq/job_util.rb:10
Sidekiq::JobUtil::TRANSIENT_ATTRIBUTES = T.let(T.unsafe(nil), Array)

# pkg:gem/sidekiq#lib/sidekiq.rb:44
Sidekiq::LICENSE = T.let(T.unsafe(nil), String)

# pkg:gem/sidekiq#lib/sidekiq/loader.rb:4
class Sidekiq::Loader
  include ::Sidekiq::Component

  # pkg:gem/sidekiq#lib/sidekiq/loader.rb:7
  def initialize(cfg = T.unsafe(nil)); end

  # Declares a block that will be executed when a Sidekiq component is fully
  # loaded. If the component has already loaded, the block is executed
  # immediately.
  #
  #   Sidekiq.loader.on_load(:api) do
  #     # extend the sidekiq API
  #   end
  #
  # pkg:gem/sidekiq#lib/sidekiq/loader.rb:22
  def on_load(name, &block); end

  # Executes all blocks registered to +name+ via on_load.
  #
  #   Sidekiq.loader.run_load_hooks(:api)
  #
  # In the case of the above example, it will execute all hooks registered for +:api+.
  #
  # pkg:gem/sidekiq#lib/sidekiq/loader.rb:44
  def run_load_hooks(name); end
end

# pkg:gem/sidekiq#lib/sidekiq/logger.rb:25
class Sidekiq::Logger < ::Logger; end

# pkg:gem/sidekiq#lib/sidekiq/logger.rb:26
module Sidekiq::Logger::Formatters; end

# pkg:gem/sidekiq#lib/sidekiq/logger.rb:27
class Sidekiq::Logger::Formatters::Base < ::Logger::Formatter
  # pkg:gem/sidekiq#lib/sidekiq/logger.rb:40
  def format_context(ctxt = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/logger.rb:36
  def tid; end
end

# pkg:gem/sidekiq#lib/sidekiq/logger.rb:28
Sidekiq::Logger::Formatters::Base::COLORS = T.let(T.unsafe(nil), Hash)

# pkg:gem/sidekiq#lib/sidekiq/logger.rb:70
class Sidekiq::Logger::Formatters::JSON < ::Sidekiq::Logger::Formatters::Base
  # pkg:gem/sidekiq#lib/sidekiq/logger.rb:71
  def call(severity, time, program_name, message); end
end

# pkg:gem/sidekiq#lib/sidekiq/logger.rb:58
class Sidekiq::Logger::Formatters::Plain < ::Sidekiq::Logger::Formatters::Base
  # pkg:gem/sidekiq#lib/sidekiq/logger.rb:59
  def call(severity, time, program_name, message); end
end

# pkg:gem/sidekiq#lib/sidekiq/logger.rb:52
class Sidekiq::Logger::Formatters::Pretty < ::Sidekiq::Logger::Formatters::Base
  # pkg:gem/sidekiq#lib/sidekiq/logger.rb:53
  def call(severity, time, program_name, message); end
end

# pkg:gem/sidekiq#lib/sidekiq/logger.rb:64
class Sidekiq::Logger::Formatters::WithoutTimestamp < ::Sidekiq::Logger::Formatters::Pretty
  # pkg:gem/sidekiq#lib/sidekiq/logger.rb:65
  def call(severity, time, program_name, message); end
end

# pkg:gem/sidekiq#lib/sidekiq/version.rb:5
Sidekiq::MAJOR = T.let(T.unsafe(nil), Integer)

# pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:4
module Sidekiq::Metrics; end

# pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:5
class Sidekiq::Metrics::Counter
  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:6
  def initialize; end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:11
  def increment; end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:15
  def value; end
end

# Implements space-efficient but statistically useful histogram storage.
# A precise time histogram stores every time. Instead we break times into a set of
# known buckets and increment counts of the associated time bucket. Even if we call
# the histogram a million times, we'll still only store 26 buckets.
# NB: needs to be thread-safe or resiliant to races.
#
# To store this data, we use Redis' BITFIELD command to store unsigned 16-bit counters
# per bucket per klass per minute. It's unlikely that most people will be executing more
# than 1000 job/sec for a full minute of a specific type (i.e. overflow 65,536).
#
# Histograms are only stored at the fine-grained level, they are not rolled up
# for longer-term buckets.
#
# pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:32
class Sidekiq::Metrics::Histogram
  include ::Enumerable

  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:74
  def initialize(klass); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:73
  def buckets; end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:65
  def each; end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:87
  def fetch(conn, now = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:69
  def label(idx); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:93
  def persist(conn, now = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:79
  def record_time(ms); end
end

# This number represents the maximum milliseconds for this bucket.
# 20 means all job executions up to 20ms, e.g. if a job takes
# 280ms, it'll increment bucket[7]. Note we can track job executions
# up to about 5.5 minutes. After that, it's assumed you're probably
# not too concerned with its performance.
#
# pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:40
Sidekiq::Metrics::Histogram::BUCKET_INTERVALS = T.let(T.unsafe(nil), Array)

# pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:56
Sidekiq::Metrics::Histogram::FETCH = T.let(T.unsafe(nil), Array)

# pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:63
Sidekiq::Metrics::Histogram::HISTOGRAM_TTL = T.let(T.unsafe(nil), Integer)

# pkg:gem/sidekiq#lib/sidekiq/metrics/shared.rb:48
Sidekiq::Metrics::Histogram::LABELS = T.let(T.unsafe(nil), Array)

# Allows caller to query for Sidekiq execution metrics within Redis.
# Caller sets a set of attributes to act as filters. {#fetch} will call
# Redis and return a Hash of results.
#
# NB: all metrics and times/dates are UTC only. We explicitly do not
# support timezones.
#
# pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:15
class Sidekiq::Metrics::Query
  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:16
  def initialize(pool: T.unsafe(nil), now: T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:76
  def for_job(klass, minutes: T.unsafe(nil), hours: T.unsafe(nil)); end

  # Get metric data for all jobs from the last hour
  #  +class_filter+: return only results for classes matching filter
  #  +minutes+: the number of fine-grained minute buckets to retrieve
  #  +hours+: the number of coarser-grained 10-minute buckets to retrieve, in hours
  #
  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:37
  def top_jobs(class_filter: T.unsafe(nil), minutes: T.unsafe(nil), hours: T.unsafe(nil)); end

  private

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:170
  def fetch_marks(time_range, granularity); end

  class << self
    # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:162
    def bkt_time_s(time, granularity); end
  end
end

# pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:125
class Sidekiq::Metrics::Query::JobResult < ::Struct
  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:126
  def initialize(granularity = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:142
  def add_hist(time, hist_result); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:134
  def add_metric(metric, time, value); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:152
  def series_avg(metric = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:146
  def total_avg(metric = T.unsafe(nil)); end
end

# pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
class Sidekiq::Metrics::Query::MarkResult < ::Struct
  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
  def bucket; end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
  def bucket=(_); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
  def label; end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
  def label=(_); end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
  def time; end

  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
  def time=(_); end

  class << self
    # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
    def [](*_arg0); end

    # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
    def inspect; end

    # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
    def keyword_init?; end

    # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
    def members; end

    # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:160
    def new(*_arg0); end
  end
end

# pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:22
Sidekiq::Metrics::Query::ROLLUPS = T.let(T.unsafe(nil), Hash)

# pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:116
class Sidekiq::Metrics::Query::Result < ::Struct
  # pkg:gem/sidekiq#lib/sidekiq/metrics/query.rb:117
  def initialize(granularity = T.unsafe(nil)); end
end

# Middleware is code configured to run before/after
# a job is processed.  It is patterned after Rack
# middleware. Middleware exists for the client side
# (pushing jobs onto the queue) as well as the server
# side (when jobs are actually processed).
#
# Callers will register middleware Classes and Sidekiq will
# create new instances of the middleware for every job. This
# is important so that instance state is not shared accidentally
# between job executions.
#
# To add middleware for the client:
#
#   Sidekiq.configure_client do |config|
#     config.client_middleware do |chain|
#       chain.add MyClientHook
#     end
#   end
#
# To modify middleware for the server, just call
# with another block:
#
#   Sidekiq.configure_server do |config|
#     config.server_middleware do |chain|
#       chain.add MyServerHook
#       chain.remove ActiveRecord
#     end
#   end
#
# To insert immediately preceding another entry:
#
#   Sidekiq.configure_client do |config|
#     config.client_middleware do |chain|
#       chain.insert_before ActiveRecord, MyClientHook
#     end
#   end
#
# To insert immediately after another entry:
#
#   Sidekiq.configure_client do |config|
#     config.client_middleware do |chain|
#       chain.insert_after ActiveRecord, MyClientHook
#     end
#   end
#
# This is an example of a minimal server middleware:
#
#   class MyServerHook
#     include Sidekiq::ServerMiddleware
#
#     def call(job_instance, msg, queue)
#       logger.info "Before job"
#       redis {|conn| conn.get("foo") } # do something in Redis
#       yield
#       logger.info "After job"
#     end
#   end
#
# This is an example of a minimal client middleware, note
# the method must return the result or the job will not push
# to Redis:
#
#   class MyClientHook
#     include Sidekiq::ClientMiddleware
#
#     def call(job_class, msg, queue, redis_pool)
#       logger.info "Before push"
#       result = yield
#       logger.info "After push"
#       result
#     end
#   end
#
# pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:79
module Sidekiq::Middleware; end

# pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:80
class Sidekiq::Middleware::Chain
  include ::Enumerable

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:89
  def initialize(config = T.unsafe(nil)); end

  # Add the given middleware to the end of the chain.
  # Sidekiq will call `klass.new(*args)` to create a clean
  # copy of your middleware for every job executed.
  #
  #   chain.add(Statsd::Metrics, { collector: "localhost:8125" })
  #
  # @param klass [Class] Your middleware class
  # @param *args [Array<Object>] Set of arguments to pass to every instance of your middleware
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:119
  def add(klass, *args); end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:163
  def clear; end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:99
  def copy_for(capsule); end

  # Iterate through each middleware in the chain
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:84
  def each(&block); end

  # @return [Boolean] if the chain contains no middleware
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:155
  def empty?; end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:95
  def entries; end

  # @return [Boolean] if the given class is already in the chain
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:149
  def exists?(klass); end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:152
  def include?(klass); end

  # Inserts +newklass+ after +oldklass+ in the chain.
  # Useful if one middleware must run after another middleware.
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:141
  def insert_after(oldklass, newklass, *args); end

  # Inserts +newklass+ before +oldklass+ in the chain.
  # Useful if one middleware must run before another middleware.
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:132
  def insert_before(oldklass, newklass, *args); end

  # Used by Sidekiq to execute the middleware at runtime
  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:169
  def invoke(*args, &block); end

  # Identical to {#add} except the middleware is added to the front of the chain.
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:125
  def prepend(klass, *args); end

  # Remove all middleware matching the given Class
  # @param klass [Class]
  #
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:107
  def remove(klass); end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:159
  def retrieve; end

  private

  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:178
  def traverse(chain, index, args, &block); end
end

# Represents each link in the middleware chain
# @api private
#
# pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:191
class Sidekiq::Middleware::Entry
  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:194
  def initialize(config, klass, *args); end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:192
  def klass; end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/chain.rb:200
  def make_new; end
end

# pkg:gem/sidekiq#lib/sidekiq.rb:43
Sidekiq::NAME = T.let(T.unsafe(nil), String)

# Sidekiq::Process represents an active Sidekiq process talking with Redis.
# Each process has a set of attributes which look like this:
#
# {
#   'hostname' => 'app-1.example.com',
#   'started_at' => <process start time>,
#   'pid' => 12345,
#   'tag' => 'myapp'
#   'concurrency' => 5,
#   'capsules' => {"default" => {"mode" => "weighted", "concurrency" => 5, "weights" => {"default" => 2, "low" => 1}}},
#   'busy' => 3,
#   'beat' => <last heartbeat>,
#   'identity' => <unique string identifying the process>,
#   'embedded' => true,
# }
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:1123
class Sidekiq::Process
  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1126
  def initialize(hash); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1138
  def [](key); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1174
  def capsules; end

  # Signal this process to log backtraces for all threads.
  # Useful if you have a frozen or deadlocked process which is
  # still sending a heartbeat.
  # This method is *asynchronous* and it can take 5-10 seconds.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1210
  def dump_threads; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1182
  def embedded?; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1145
  def id; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1142
  def identity; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1134
  def labels; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1219
  def leader?; end

  # deprecated, use capsules below
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1148
  def queues; end

  # Signal this process to stop processing new jobs.
  # It will continue to execute jobs it has already fetched.
  # This method is *asynchronous* and it can take 5-10
  # seconds for the process to quiet.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1190
  def quiet!; end

  # Signal this process to shutdown.
  # It will shutdown within its configured :timeout value, default 25 seconds.
  # This method is *asynchronous* and it can take 5-10
  # seconds for the process to start shutting down.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1200
  def stop!; end

  # @return [Boolean] true if this process is quiet or shutting down
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1215
  def stopping?; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1130
  def tag; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1178
  def version; end

  # deprecated, use capsules below
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1158
  def weights; end

  private

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1225
  def signal(sig); end
end

# Enumerates the set of Sidekiq processes which are actively working
# right now.  Each process sends a heartbeat to Redis every 5 seconds
# so this set should be relatively accurate, barring network partitions.
#
# @yieldparam [Sidekiq::Process]
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:984
class Sidekiq::ProcessSet
  include ::Enumerable

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1007
  def initialize(clean_plz = T.unsafe(nil)); end

  # Cleans up dead processes recorded in Redis.
  # Returns the number of processes cleaned.
  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1015
  def cleanup; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1039
  def each; end

  # Returns the identity of the current cluster leader or "" if no leader.
  # This is a Sidekiq Enterprise feature, will always return "" in Sidekiq
  # or Sidekiq Pro.
  # @return [String] Identity of cluster leader
  # @return [String] empty string if no leader
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1097
  def leader; end

  # This method is not guaranteed accurate since it does not prune the set
  # based on current heartbeat.  #each does that and ensures the set only
  # contains Sidekiq processes which have sent a heartbeat within the last
  # 60 seconds.
  # @return [Integer] current number of registered Sidekiq processes
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1074
  def size; end

  # Total number of threads available to execute jobs.
  # For Sidekiq Enterprise customers this number (in production) must be
  # less than or equal to your licensed concurrency.
  # @return [Integer] the sum of process concurrency
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1082
  def total_concurrency; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1090
  def total_rss; end

  # @return [Integer] total amount of RSS memory consumed by Sidekiq processes
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1087
  def total_rss_in_kb; end

  class << self
    # pkg:gem/sidekiq#lib/sidekiq/api.rb:987
    def [](identity); end
  end
end

# pkg:gem/sidekiq#lib/sidekiq/api.rb:1384
class Sidekiq::ProfileRecord
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1387
  def initialize(arr); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1401
  def data; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1385
  def elapsed; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1385
  def jid; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1397
  def key; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1385
  def size; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1385
  def started_at; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1385
  def token; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1385
  def type; end
end

# pkg:gem/sidekiq#lib/sidekiq/api.rb:1352
class Sidekiq::ProfileSet
  include ::Enumerable

  # This is a point in time/snapshot API, you'll need to instantiate a new instance
  # if you want to fetch newer records.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1357
  def initialize; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1370
  def each(&block); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1366
  def size; end
end

# Represents a queue within Sidekiq.
# Allows enumeration of all jobs within the queue
# and deletion of jobs. NB: this queue data is real-time
# and is changing within Redis moment by moment.
#
#   queue = Sidekiq::Queue.new("mailer")
#   queue.each do |job|
#     job.klass # => 'MyWorker'
#     job.args # => [1, 2, 3]
#     job.delete if job.jid == 'abcdef1234567890'
#   end
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:285
class Sidekiq::Queue
  include ::Enumerable
  include ::Sidekiq::ApiUtils

  # @param name [String] the name of the queue
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:301
  def initialize(name = T.unsafe(nil)); end

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:383
  def as_json(options = T.unsafe(nil)); end

  # delete all jobs within this queue
  # @return [Boolean] true
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:370
  def clear; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:334
  def each; end

  # Find the job with the given JID within this queue.
  #
  # This is a *slow, inefficient* operation.  Do not use under
  # normal conditions.
  #
  # @param jid [String] the job_id to look for
  # @return [Sidekiq::JobRecord]
  # @return [nil] if not found
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:364
  def find_job(jid); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:298
  def id; end

  # Calculates this queue's latency, the difference in seconds since the oldest
  # job in the queue was enqueued.
  #
  # @return [Float] in seconds
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:324
  def latency; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:297
  def name; end

  # @return [Boolean] if the queue is currently paused
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:315
  def paused?; end

  # The current size of the queue within Redis.
  # This value is real-time and can change between calls.
  #
  # @return [Integer] the size
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:310
  def size; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:379
  def 💣; end

  class << self
    # Fetch all known queues within Redis.
    #
    # @return [Array<Sidekiq::Queue>]
    #
    # pkg:gem/sidekiq#lib/sidekiq/api.rb:293
    def all; end
  end
end

# pkg:gem/sidekiq#lib/sidekiq/test_api.rb:107
module Sidekiq::Queues
  class << self
    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:174
    def [](queue); end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:202
    def clear_all; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:197
    def clear_for(queue, klass); end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:192
    def delete_for(jid, queue, klass); end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:187
    def jobs_by_class; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:183
    def jobs_by_queue; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:190
    def jobs_by_worker; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:178
    def push(queue, klass, job); end
  end
end

# pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:7
class Sidekiq::RedisClientAdapter
  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:62
  def initialize(options); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:78
  def new_client; end

  private

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:84
  def client_opts(options); end
end

# pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:8
Sidekiq::RedisClientAdapter::BaseError = RedisClient::Error

# pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:9
Sidekiq::RedisClientAdapter::CommandError = RedisClient::CommandError

# pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:54
class Sidekiq::RedisClientAdapter::CompatClient < ::RedisClient::Decorator::Client
  include ::Sidekiq::RedisClientAdapter::CompatMethods

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:57
  def config; end
end

# pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:54
class Sidekiq::RedisClientAdapter::CompatClient::Pipeline < ::RedisClient::Decorator::Pipeline
  include ::Sidekiq::RedisClientAdapter::CompatMethods
end

# pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:14
module Sidekiq::RedisClientAdapter::CompatMethods
  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def bitfield(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def bitfield_ro(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def del(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:19
  def evalsha(sha, keys, argv); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def exists(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def expire(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def flushdb(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def get(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def hdel(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def hget(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def hgetall(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def hincrby(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def hlen(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def hmget(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def hset(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def hsetnx(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def incr(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def incrby(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:15
  def info; end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def lindex(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def llen(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def lmove(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def lpop(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def lpush(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def lrange(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def lrem(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def mget(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def mset(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def ping(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def pttl(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def publish(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def rpop(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def rpush(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def sadd(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def scard(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def script(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def set(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def sismember(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def smembers(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def srem(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def ttl(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def type(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def unlink(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def zadd(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def zcard(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def zincrby(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def zrange(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def zrem(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def zremrangebyrank(*args, **kwargs); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:34
  def zremrangebyscore(*args, **kwargs); end

  private

  # this allows us to use methods like `conn.hmset(...)` instead of having to use
  # redis-client's native `conn.call("hmset", ...)`
  #
  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:43
  def method_missing(*args, **, &block); end

  # pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:49
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

# this is the set of Redis commands used by Sidekiq. Not guaranteed
# to be comprehensive, we use this as a performance enhancement to
# avoid calling method_missing on most commands
#
# pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:26
Sidekiq::RedisClientAdapter::CompatMethods::USED_COMMANDS = T.let(T.unsafe(nil), Array)

# You can add/remove items or clear the whole thing if you don't want deprecation warnings.
#
# pkg:gem/sidekiq#lib/sidekiq/redis_client_adapter.rb:12
Sidekiq::RedisClientAdapter::DEPRECATED_COMMANDS = T.let(T.unsafe(nil), Set)

# pkg:gem/sidekiq#lib/sidekiq/redis_connection.rb:8
module Sidekiq::RedisConnection
  class << self
    # pkg:gem/sidekiq#lib/sidekiq/redis_connection.rb:10
    def create(options = T.unsafe(nil)); end

    private

    # pkg:gem/sidekiq#lib/sidekiq/redis_connection.rb:52
    def deep_symbolize_keys(object); end

    # pkg:gem/sidekiq#lib/sidekiq/redis_connection.rb:92
    def determine_redis_provider; end

    # pkg:gem/sidekiq#lib/sidekiq/redis_connection.rb:65
    def scrub(options); end

    # Wrap hard-coded passwords in a Proc to avoid logging the value
    #
    # pkg:gem/sidekiq#lib/sidekiq/redis_connection.rb:44
    def wrap(pwd); end
  end
end

# The set of retries within Sidekiq.
# See the API wiki page for usage notes and examples.
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:920
class Sidekiq::RetrySet < ::Sidekiq::JobSet
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:921
  def initialize; end
end

# The set of scheduled jobs within Sidekiq.
# See the API wiki page for usage notes and examples.
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:910
class Sidekiq::ScheduledSet < ::Sidekiq::JobSet
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:911
  def initialize; end
end

# Server-side middleware must import this Module in order
# to get access to server resources during `call`.
#
# pkg:gem/sidekiq#lib/sidekiq/middleware/modules.rb:6
module Sidekiq::ServerMiddleware
  # pkg:gem/sidekiq#lib/sidekiq/middleware/modules.rb:7
  def config; end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/modules.rb:7
  def config=(_arg0); end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/modules.rb:12
  def logger; end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/modules.rb:16
  def redis(&block); end

  # pkg:gem/sidekiq#lib/sidekiq/middleware/modules.rb:8
  def redis_pool; end
end

# We are shutting down Sidekiq but what about threads that
# are working on some long job?  This error is
# raised in jobs that have not finished within the hard
# timeout limit.  This is needed to rollback db transactions,
# otherwise Ruby's Thread#kill will commit.  See #377.
# DO NOT RESCUE THIS ERROR IN YOUR JOBS
#
# pkg:gem/sidekiq#lib/sidekiq.rb:158
class Sidekiq::Shutdown < ::Interrupt; end

# Represents a job within a Redis sorted set where the score
# represents a timestamp associated with the job. This timestamp
# could be the scheduled time for it to run (e.g. scheduled set),
# or the expiration date after which the entry should be deleted (e.g. dead set).
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:590
class Sidekiq::SortedEntry < ::Sidekiq::JobRecord
  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:595
  def initialize(parent, score, item); end

  # Enqueue this job from the scheduled or dead set so it will
  # be executed at some point in the near future.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:635
  def add_to_queue; end

  # The timestamp associated with this entry
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:610
  def at; end

  # remove this entry from the sorted set
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:615
  def delete; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:659
  def error?; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:605
  def id; end

  # Move this job from its current set into the Dead set.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:653
  def kill; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:591
  def parent; end

  # Change the scheduled time for this job.
  #
  # @param at [Time] the new timestamp for this job
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:626
  def reschedule(at); end

  # enqueue this job from the retry set so it will be executed
  # at some point in the near future.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:644
  def retry; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:601
  def score; end

  private

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:665
  def remove_job(&); end
end

# Base class for all sorted sets within Sidekiq.
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:671
class Sidekiq::SortedSet
  include ::Enumerable

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:680
  def initialize(name); end

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:718
  def as_json(options = T.unsafe(nil)); end

  # @return [Boolean] always true
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:708
  def clear; end

  # Redis key of the set
  # @!attribute [r] Name
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:676
  def name; end

  # Scan through each element of the sorted set, yielding each to the supplied block.
  # Please see Redis's <a href="https://redis.io/commands/scan/">SCAN documentation</a> for implementation details.
  #
  # @param match [String] a snippet or regexp to filter matches.
  # @param count [Integer] number of elements to retrieve at a time, default 100
  # @yieldparam [Sidekiq::SortedEntry] each entry
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:696
  def scan(match, count = T.unsafe(nil)); end

  # real-time size of the set, will change
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:686
  def size; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:714
  def 💣; end
end

# Retrieve runtime statistics from Redis regarding
# this Sidekiq cluster.
#
#   stat = Sidekiq::Stats.new
#   stat.processed
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:44
class Sidekiq::Stats
  include ::Sidekiq::ApiUtils

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:51
  def initialize; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:71
  def dead_size; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:87
  def default_queue_latency; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:75
  def enqueued; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:59
  def failed; end

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:209
  def fetch_stats!; end

  # O(1) redis calls
  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:144
  def fetch_stats_fast!; end

  # O(number of processes + number of queues) redis calls
  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:183
  def fetch_stats_slow!; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:55
  def processed; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:79
  def processes_size; end

  # More detailed information about each queue: name, size, latency, paused status
  # @return [Array<QueueSummary>]
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:109
  def queue_summaries; end

  # @return [Hash{String => Integer}] a hash of queue names to their lengths
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:92
  def queues; end

  # @api private
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:215
  def reset(*stats); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:67
  def retry_size; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:63
  def scheduled_size; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:83
  def workers_size; end

  private

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:231
  def stat(s); end
end

# pkg:gem/sidekiq#lib/sidekiq/api.rb:236
class Sidekiq::Stats::History
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:237
  def initialize(days_previous, start_date = T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:248
  def failed; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:244
  def processed; end

  private

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:254
  def date_stat_hash(stat); end
end

# pkg:gem/sidekiq#lib/sidekiq/api.rb:45
class Sidekiq::Stats::QueueSummary < ::Data
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:45
  def latency; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:45
  def name; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:45
  def paused; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:46
  def paused?; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:45
  def size; end

  class << self
    # pkg:gem/sidekiq#lib/sidekiq/api.rb:45
    def [](*_arg0); end

    # pkg:gem/sidekiq#lib/sidekiq/api.rb:45
    def inspect; end

    # pkg:gem/sidekiq#lib/sidekiq/api.rb:45
    def members; end

    # pkg:gem/sidekiq#lib/sidekiq/api.rb:45
    def new(*_arg0); end
  end
end

# pkg:gem/sidekiq#lib/sidekiq/test_api.rb:7
class Sidekiq::Testing
  class << self
    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:10
    def __global_test_mode; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:10
    def __global_test_mode=(_arg0); end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:36
    def __local_test_mode; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:40
    def __local_test_mode=(value); end

    # Calling without a block sets the global test mode, affecting
    # all threads. Calling with a block only affects the current Thread.
    #
    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:14
    def __set_test_mode(mode); end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:32
    def __test_mode; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:44
    def disable!(&block); end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:60
    def disabled?; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:56
    def enabled?; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:48
    def fake!(&block); end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:64
    def fake?; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:52
    def inline!(&block); end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:68
    def inline?; end

    # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:72
    def server_middleware; end
  end
end

# pkg:gem/sidekiq#lib/sidekiq/test_api.rb:8
class Sidekiq::Testing::TestModeAlreadySetError < ::RuntimeError; end

# pkg:gem/sidekiq#lib/sidekiq/test_api.rb:82
module Sidekiq::TestingClient
  private

  # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:83
  def atomic_push(conn, payloads); end
end

# pkg:gem/sidekiq#lib/sidekiq/test_api.rb:319
module Sidekiq::TestingExtensions
  # pkg:gem/sidekiq#lib/sidekiq/test_api.rb:320
  def jobs_for(klass); end
end

# pkg:gem/sidekiq#lib/sidekiq/transaction_aware_client.rb:7
class Sidekiq::TransactionAwareClient
  # pkg:gem/sidekiq#lib/sidekiq/transaction_aware_client.rb:8
  def initialize(pool: T.unsafe(nil), config: T.unsafe(nil)); end

  # pkg:gem/sidekiq#lib/sidekiq/transaction_aware_client.rb:18
  def batching?; end

  # pkg:gem/sidekiq#lib/sidekiq/transaction_aware_client.rb:22
  def push(item); end

  # We don't provide transactionality for push_bulk because we don't want
  # to hold potentially hundreds of thousands of job records in memory due to
  # a long running enqueue process.
  #
  # pkg:gem/sidekiq#lib/sidekiq/transaction_aware_client.rb:37
  def push_bulk(items); end
end

# pkg:gem/sidekiq#lib/sidekiq/version.rb:4
Sidekiq::VERSION = T.let(T.unsafe(nil), String)

# Sidekiq::Work represents a job which is currently executing.
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:1319
class Sidekiq::Work
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1323
  def initialize(pid, tid, hsh); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1338
  def job; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1342
  def payload; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1320
  def process_id; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1330
  def queue; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1334
  def run_at; end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1321
  def thread_id; end
end

# The WorkSet stores the work being done by this Sidekiq cluster.
# It tracks the process and thread working on each job.
#
# WARNING WARNING WARNING
#
# This is live data that can change every millisecond.
# If you call #size => 5 and then expect #each to be
# called 5 times, you're going to have a bad time.
#
#    works = Sidekiq::WorkSet.new
#    works.size => 2
#    works.each do |process_id, thread_id, work|
#      # process_id is a unique identifier per Sidekiq process
#      # thread_id is a unique identifier per thread
#      # work is a `Sidekiq::Work` instance that has the following accessor methods.
#      # [work.queue, work.run_at, work.payload]
#    end
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:1255
class Sidekiq::WorkSet
  include ::Enumerable

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1258
  def each(&block); end

  # Find the work which represents a job with the given JID.
  # *This is a slow O(n) operation*.  Do not use for app logic.
  #
  # @param jid [String] the job identifier
  # @return [Sidekiq::Work] the work or nil
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1308
  def find_work(jid); end

  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1315
  def find_work_by_jid(jid); end

  # Note that #size is only as accurate as Sidekiq's heartbeat,
  # which happens every 5 seconds.  It is NOT real-time.
  #
  # Not very efficient if you have lots of Sidekiq
  # processes but the alternative is a global counter
  # which can easily get out of sync with crashy processes.
  #
  # pkg:gem/sidekiq#lib/sidekiq/api.rb:1287
  def size; end
end

# Sidekiq::Job is a new alias for Sidekiq::Worker as of Sidekiq 6.3.0.
# Use `include Sidekiq::Job` rather than `include Sidekiq::Worker`.
#
# The term "worker" is too generic and overly confusing, used in several
# different contexts meaning different things. Many people call a Sidekiq
# process a "worker". Some people call the thread that executes jobs a
# "worker". This change brings Sidekiq closer to ActiveJob where your job
# classes extend ApplicationJob.
#
# pkg:gem/sidekiq#lib/sidekiq/worker_compatibility_alias.rb:12
Sidekiq::Worker = Sidekiq::Job

# Since "worker" is a nebulous term, we've deprecated the use of this class name.
# Is "worker" a process, a type of job, a thread? Undefined!
# WorkSet better describes the data.
#
# pkg:gem/sidekiq#lib/sidekiq/api.rb:1350
Sidekiq::Workers = Sidekiq::WorkSet
