# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `smart_todo` gem.
# Please instead update this file by running `bin/tapioca gem smart_todo`.


# pkg:gem/smart_todo#lib/smart_todo_cop.rb:6
module RuboCop; end

# pkg:gem/smart_todo#lib/smart_todo_cop.rb:7
module RuboCop::Cop; end

# pkg:gem/smart_todo#lib/smart_todo_cop.rb:8
module RuboCop::Cop::SmartTodo; end

# A RuboCop used to restrict the usage of regular TODO comments in code.
# This Cop does not run by default. It should be added to the RuboCop host's configuration file.
#
# @see https://rubocop.readthedocs.io/en/latest/extensions/#loading-extensions
#
# pkg:gem/smart_todo#lib/smart_todo_cop.rb:13
class RuboCop::Cop::SmartTodo::SmartTodoCop < ::RuboCop::Cop::Base
  # @param processed_source [RuboCop::ProcessedSource]
  # @return [void]
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:22
  def on_new_investigation; end

  private

  # @param assignees [Array]
  # @return [Array]
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:63
  def invalid_assignees(assignees); end

  # @param comment [String]
  # @return [SmartTodo::Parser::Visitor]
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:49
  def metadata(comment); end

  # @param metadata [SmartTodo::Parser::Visitor]
  # @return [true, false]
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:55
  def smart_todo?(metadata); end

  # @param args [Array]
  # @return [String, nil] Returns error message if date is invalid, nil if valid
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:86
  def validate_date_args(args); end

  # @param events [Array<SmartTodo::Todo::CallNode>]
  # @return [Array<String>]
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:69
  def validate_events(events); end

  # Helper method for validating fixed arity events
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:129
  def validate_fixed_arity_args(args, expected_count, event_name, arg_names); end

  # Helper method for validating gem-related events
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:140
  def validate_gem_args(args, event_name); end

  # @param args [Array]
  # @return [String, nil] Returns error message if arguments are invalid, nil if valid
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:114
  def validate_gem_bump_args(args); end

  # @param args [Array]
  # @return [String, nil] Returns error message if arguments are invalid, nil if valid
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:108
  def validate_gem_release_args(args); end

  # @param args [Array]
  # @return [String, nil] Returns error message if arguments are invalid, nil if valid
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:96
  def validate_issue_close_args(args); end

  # @param event_type [Symbol]
  # @return [String]
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:80
  def validate_method(event_type); end

  # @param args [Array]
  # @return [String, nil] Returns error message if arguments are invalid, nil if valid
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:102
  def validate_pull_request_close_args(args); end

  # @param args [Array]
  # @return [String, nil] Returns error message if arguments are invalid, nil if valid
  #
  # pkg:gem/smart_todo#lib/smart_todo_cop.rb:120
  def validate_ruby_version_args(args); end
end

# pkg:gem/smart_todo#lib/smart_todo_cop.rb:14
RuboCop::Cop::SmartTodo::SmartTodoCop::HELP = T.let(T.unsafe(nil), String)

# pkg:gem/smart_todo#lib/smart_todo_cop.rb:16
RuboCop::Cop::SmartTodo::SmartTodoCop::INVESTIGATED_TAGS = T.let(T.unsafe(nil), Array)

# pkg:gem/smart_todo#lib/smart_todo_cop.rb:15
RuboCop::Cop::SmartTodo::SmartTodoCop::MSG = T.let(T.unsafe(nil), String)

# pkg:gem/smart_todo#lib/smart_todo_cop.rb:18
RuboCop::Cop::SmartTodo::SmartTodoCop::TODO_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/smart_todo#lib/smart_todo/version.rb:3
module SmartTodo; end

# This class is the entrypoint of the SmartTodo library and is responsible
# to retrieve the command line options as well as iterating over each files/directories
# to run the +CommentParser+ on.
#
# pkg:gem/smart_todo#lib/smart_todo/cli.rb:10
class SmartTodo::CLI
  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:11
  def initialize(dispatcher = T.unsafe(nil)); end

  # @return [OptionParser] an instance of OptionParser
  #
  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:57
  def define_options; end

  # @return [Class] a Dispatchers::Base subclass
  #
  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:76
  def dispatcher; end

  # @param path [String] a path to a file or directory
  # @return [Array<String>] all the directories the parser should run on
  #
  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:82
  def normalize_path(path); end

  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:90
  def process_todos(todos); end

  # @param args [Array<String>]
  #
  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:18
  def run(args = T.unsafe(nil)); end

  # @raise [ArgumentError] In case an option needed by a dispatcher wasn't provided.
  #
  # @return [void]
  #
  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:52
  def validate_options!; end

  private

  # @param event_message [String] the original event message
  # @param todo [Todo] the todo object that may contain context
  # @param event [Event] the event that was met
  # @param events [Events] the events instance for fetching issue context
  # @return [String] the event message, potentially with context appended
  #
  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:127
  def append_context_if_applicable(event_message, todo, event, events); end

  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:143
  def process_dispatches(dispatches); end

  # @param todo [Todo] the todo object to check for context
  # @param event [Event] the event to check
  # @return [Boolean] true if context should be applied, false otherwise
  #
  # pkg:gem/smart_todo#lib/smart_todo/cli.rb:139
  def should_apply_context?(todo, event); end
end

# pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:4
class SmartTodo::CommentParser
  # pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:10
  def initialize; end

  # pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:15
  def parse(source, filepath = T.unsafe(nil)); end

  # pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:19
  def parse_file(filepath); end

  # pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:8
  def todos; end

  private

  # pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:43
  def inline?(comment); end

  # pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:52
  def parse_comments(comments, filepath); end

  class << self
    # pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:33
    def parse(source); end
  end
end

# pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:5
SmartTodo::CommentParser::SUPPORTED_TAGS = T.let(T.unsafe(nil), Array)

# pkg:gem/smart_todo#lib/smart_todo/comment_parser.rb:6
SmartTodo::CommentParser::TAG_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/smart_todo#lib/smart_todo.rb:14
module SmartTodo::Dispatchers; end

# pkg:gem/smart_todo#lib/smart_todo/dispatchers/base.rb:5
class SmartTodo::Dispatchers::Base
  # @param event_message [String] the success message associated
  #   a specific event
  # @param todo_node [SmartTodo::Parser::TodoNode]
  # @param file [String] the file containing the TODO
  # @param options [Hash]
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/base.rb:38
  def initialize(event_message, todo_node, file, options); end

  # This method gets called when a TODO reminder is expired and needs to be delivered.
  # Dispatchers should implement this method to deliver the message where they need.
  #
  # @return void
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/base.rb:50
  def dispatch; end

  private

  # Hello message for user actually existing in the organization
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/base.rb:91
  def existing_user; end

  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/base.rb:95
  def repo; end

  # Prepare the content of the message to send to the TODO assignee
  #
  # @param user [Hash] contain information about a user
  # @param assignee [String] original string handle the slack message should be sent
  # @return [String]
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/base.rb:61
  def slack_message(user, assignee); end

  # Message in case a TODO's assignee doesn't exist in the Slack organization
  #
  # @param user [Hash]
  # @return [String]
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/base.rb:86
  def unexisting_user(assignee); end

  class << self
    # Factory pattern to retrieve the right dispatcher class.
    #
    # @param dispatcher [String]
    #
    # @return [Class]
    #
    # pkg:gem/smart_todo#lib/smart_todo/dispatchers/base.rb:12
    def class_for(dispatcher); end

    # Subclasses should define what options from the CLI they need in order
    # to properly deliver the message. For instance the Slack dispatcher
    # requires an API key.
    #
    # @param _options [Hash]
    #
    # @return void
    #
    # pkg:gem/smart_todo#lib/smart_todo/dispatchers/base.rb:28
    def validate_options!(_options); end
  end
end

# A simple dispatcher that will output the reminder.
#
# pkg:gem/smart_todo#lib/smart_todo/dispatchers/output.rb:6
class SmartTodo::Dispatchers::Output < ::SmartTodo::Dispatchers::Base
  # @return void
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/output.rb:12
  def dispatch; end

  class << self
    # pkg:gem/smart_todo#lib/smart_todo/dispatchers/output.rb:8
    def validate_options!(_); end
  end
end

# Dispatcher that sends TODO reminders on Slack. Assignees can be either individual
# (using the associated slack email address) or a channel.
#
# pkg:gem/smart_todo#lib/smart_todo/dispatchers/slack.rb:7
class SmartTodo::Dispatchers::Slack < ::SmartTodo::Dispatchers::Base
  # Make a Slack API call to dispatch the message to each assignee
  #
  # @raise [SlackClient::Error] in case the Slack API returns an error
  #   other than `users_not_found`
  #
  # @return [Array] Slack response for each assignee a message was sent to
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/slack.rb:23
  def dispatch; end

  # Make a Slack API call to dispatch the message to the user or channel
  #
  # @raise [SlackClient::Error] in case the Slack API returns an error
  #   other than `users_not_found`
  #
  # @param [String] the assignee handle string
  # @return [Hash] the Slack response
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/slack.rb:36
  def dispatch_one(assignee); end

  private

  # @return [SlackClient] an instance of SlackClient
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/slack.rb:72
  def client; end

  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/slack.rb:76
  def handle_slack_error(error, message); end

  # Returns a formatted hash containing either the user id of a slack user or
  # the channel the message should be sent to.
  #
  # @return [Hash] a suited hash containing the user ID for a given individual or a slack channel
  #
  # pkg:gem/smart_todo#lib/smart_todo/dispatchers/slack.rb:58
  def slack_user_or_channel(assignee); end

  class << self
    # pkg:gem/smart_todo#lib/smart_todo/dispatchers/slack.rb:9
    def validate_options!(options); end
  end
end

# This module contains all the methods accessible for SmartTodo comments.
# It is meant to be reopened by the host application in order to define
# its own events.
#
# An event needs to return a +String+ containing the message that will be
# sent to the TODO assignee or +false+ in case the event hasn't been met.
#
# @example Adding a custom event
#   module SmartTodo
#     class Events
#       def trello_card_close(card)
#         ...
#       end
#     end
#   end
#
#   TODO(on: trello_card_close(381), to: 'john@example.com')
#
# pkg:gem/smart_todo#lib/smart_todo/events.rb:28
class SmartTodo::Events
  # pkg:gem/smart_todo#lib/smart_todo/events.rb:29
  def initialize(now: T.unsafe(nil), spec_set: T.unsafe(nil), current_ruby_version: T.unsafe(nil)); end

  # Check if the +date+ is in the past
  #
  # @param on_date [String] a string parsable by Time.parse
  # @return [false, String]
  #
  # pkg:gem/smart_todo#lib/smart_todo/events.rb:41
  def date(on_date); end

  # Check if +gem_name+ was bumped to the +requirements+ expected
  #
  # @example Expecting a specific version
  #   gem_bump('rails', '6.0')
  #
  # @example Expecting a version in the 5.x.x series
  #   gem_bump('rails', '> 5.2', '< 6')
  #
  # @param gem_name [String]
  # @param requirements [Array<String>] a list of version specifiers
  # @return [false, String]
  #
  # pkg:gem/smart_todo#lib/smart_todo/events.rb:93
  def gem_bump(gem_name, *requirements); end

  # Check if a new version of +gem_name+ was released with the +requirements+ expected
  #
  # @example Expecting a specific version
  #   gem_release('rails', '6.0')
  #
  # @example Expecting a version in the 5.x.x series
  #   gem_release('rails', '> 5.2', '< 6')
  #
  # @param gem_name [String]
  # @param requirements [Array<String>] a list of version specifiers
  # @return [false, String]
  #
  # pkg:gem/smart_todo#lib/smart_todo/events.rb:61
  def gem_release(gem_name, *requirements); end

  # Check if the issue +issue_number+ is closed
  #
  # @param organization [String] the GitHub organization name
  # @param repo [String] the GitHub repo name
  # @param issue_number [String, Integer]
  # @return [false, String]
  #
  # pkg:gem/smart_todo#lib/smart_todo/events.rb:118
  def issue_close(organization, repo, issue_number); end

  # Retrieve context information for an issue
  # This is used when a TODO has a context: issue() attribute
  #
  # @param organization [String] the GitHub organization name
  # @param repo [String] the GitHub repo name
  # @param issue_number [String, Integer]
  # @return [String, nil]
  #
  # pkg:gem/smart_todo#lib/smart_todo/events.rb:173
  def issue_context(organization, repo, issue_number); end

  # Check if the pull request +pr_number+ is closed
  #
  # @param organization [String] the GitHub organization name
  # @param repo [String] the GitHub repo name
  # @param pr_number [String, Integer]
  # @return [false, String]
  #
  # pkg:gem/smart_todo#lib/smart_todo/events.rb:145
  def pull_request_close(organization, repo, pr_number); end

  # Check if the installed ruby version meets requirements.
  #
  # @param requirements [Array<String>] a list of version specifiers
  # @return [false, String]
  #
  # pkg:gem/smart_todo#lib/smart_todo/events.rb:196
  def ruby_version(*requirements); end

  private

  # pkg:gem/smart_todo#lib/smart_todo/events.rb:250
  def current_ruby_version; end

  # @return [String, nil]
  #
  # pkg:gem/smart_todo#lib/smart_todo/events.rb:236
  def github_authorization_token(organization, repo); end

  # pkg:gem/smart_todo#lib/smart_todo/events.rb:220
  def github_client; end

  # pkg:gem/smart_todo#lib/smart_todo/events.rb:224
  def github_headers(organization, repo); end

  # pkg:gem/smart_todo#lib/smart_todo/events.rb:208
  def now; end

  # pkg:gem/smart_todo#lib/smart_todo/events.rb:216
  def rubygems_client; end

  # pkg:gem/smart_todo#lib/smart_todo/events.rb:212
  def spec_set; end
end

# pkg:gem/smart_todo#lib/smart_todo/events.rb:233
SmartTodo::Events::GITHUB_TOKEN = T.let(T.unsafe(nil), String)

# @api private
#
# pkg:gem/smart_todo#lib/smart_todo/http_client_builder.rb:7
class SmartTodo::HttpClientBuilder
  class << self
    # pkg:gem/smart_todo#lib/smart_todo/http_client_builder.rb:9
    def build(endpoint); end
  end
end

# A simple client around the Slack API.
#
# @example Sending a  message to a user.
#   SmartTodo::SlackClient.new.post_message('#general', 'Hello!')
#
# pkg:gem/smart_todo#lib/smart_todo/slack_client.rb:12
class SmartTodo::SlackClient
  # @param slack_token [String]
  #
  # pkg:gem/smart_todo#lib/smart_todo/slack_client.rb:27
  def initialize(slack_token); end

  # Retrieve the Slack ID of a user from his email
  #
  # @param email [String]
  # @param min_sleep [Integer] - the minimum sleep time in seconds in case of rate limiting
  # @return [Hash]
  #
  # @raise [Net::HTTPError] in case the request to Slack failed
  # @raise [SlackClient::Error] in case Slack returns a { ok: false } in the body
  #
  # @see https://api.slack.com/methods/users.lookupByEmail
  #
  # pkg:gem/smart_todo#lib/smart_todo/slack_client.rb:42
  def lookup_user_by_email(email, min_sleep = T.unsafe(nil)); end

  # Send a message to a Slack channel or to a user
  #
  # @param channel [String] The Slack channel or the user ID
  # @param text [String] The message to send
  # @return [Hash]
  #
  # @raise [Net::HTTPError] in case the request to Slack failed
  # @raise [SlackClient::Error] in case Slack returns a { ok: false } in the body
  #
  # @see https://api.slack.com/methods/chat.postMessage
  #
  # pkg:gem/smart_todo#lib/smart_todo/slack_client.rb:58
  def post_message(channel, text); end

  private

  # The default headers required by Slack
  #
  # @return [Hash]
  #
  # pkg:gem/smart_todo#lib/smart_todo/slack_client.rb:102
  def default_headers; end

  # @param request [Net::HTTPRequest]
  # @param max_attempts [Integer] - the maximum number of attempts to make
  # @param min_sleep [Integer] - the minimum sleep time in seconds in case of rate limiting
  #
  # @raise [Net::HTTPError] in case the request to Slack failed
  # @raise [SlackClient::Error] in case Slack returns a { ok: false } in the body
  #
  # pkg:gem/smart_todo#lib/smart_todo/slack_client.rb:73
  def dispatch(request, max_attempts = T.unsafe(nil), min_sleep = T.unsafe(nil)); end
end

# A generic error class raised when the Slack API returns back a 200
# but there was a problem (permission issues ...)
#
# pkg:gem/smart_todo#lib/smart_todo/slack_client.rb:15
class SmartTodo::SlackClient::Error < ::StandardError
  # @param response_body [Hash] the parsed response body from Slack
  #
  # pkg:gem/smart_todo#lib/smart_todo/slack_client.rb:19
  def initialize(response_body); end

  # pkg:gem/smart_todo#lib/smart_todo/slack_client.rb:16
  def error_code; end
end

# pkg:gem/smart_todo#lib/smart_todo/todo.rb:4
class SmartTodo::Todo
  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:9
  def initialize(source, filepath = T.unsafe(nil)); end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:22
  def <<(source); end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:6
  def assignees; end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:5
  def comment; end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:7
  def context; end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:7
  def context=(_arg0); end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:6
  def errors; end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:6
  def events; end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:5
  def filepath; end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:5
  def indent; end

  private

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:104
  def parse(source); end
end

# pkg:gem/smart_todo#lib/smart_todo/todo.rb:26
class SmartTodo::Todo::CallNode
  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:29
  def initialize(method_name, arguments, location); end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:27
  def arguments; end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:27
  def location; end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:27
  def method_name; end
end

# pkg:gem/smart_todo#lib/smart_todo/todo.rb:36
class SmartTodo::Todo::Compiler < ::Prism::Compiler
  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:39
  def initialize(metadata); end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:37
  def metadata; end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:44
  def visit_call_node(node); end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:48
  def visit_integer_node(node); end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:52
  def visit_keyword_hash_node(node); end

  # pkg:gem/smart_todo#lib/smart_todo/todo.rb:97
  def visit_string_node(node); end
end

# pkg:gem/smart_todo#lib/smart_todo/version.rb:4
SmartTodo::VERSION = T.let(T.unsafe(nil), String)
