# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `vernier` gem.
# Please instead update this file by running `bin/tapioca gem vernier`.


# pkg:gem/vernier#lib/vernier/version.rb:3
module Vernier
  class << self
    # pkg:gem/vernier#lib/vernier/marker.rb:3
    def memory_rss; end

    # pkg:gem/vernier#lib/vernier.rb:24
    def profile(mode: T.unsafe(nil), **collector_options); end

    # pkg:gem/vernier#lib/vernier.rb:40
    def run(mode: T.unsafe(nil), **collector_options); end

    # pkg:gem/vernier#lib/vernier.rb:45
    def start_profile(mode: T.unsafe(nil), **collector_options); end

    # pkg:gem/vernier#lib/vernier.rb:57
    def stop_profile; end

    # pkg:gem/vernier#lib/vernier.rb:39
    def trace(mode: T.unsafe(nil), **collector_options); end

    # pkg:gem/vernier#lib/vernier.rb:66
    def trace_retained(**profile_options, &block); end
  end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::Collector
  # pkg:gem/vernier#lib/vernier/collector.rb:114
  def initialize(mode, options = T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/collector.rb:166
  def add_marker(name:, start:, finish:, thread: T.unsafe(nil), phase: T.unsafe(nil), data: T.unsafe(nil)); end

  # Get the current time.
  #
  # This method returns the current time from Process.clock_gettime in
  # integer nanoseconds.  It's the same time used by Vernier internals and
  # can be used to generate timestamps for custom markers.
  #
  # pkg:gem/vernier#lib/vernier/collector.rb:162
  def current_time; end

  # Record an interval with a category and name.  Yields to a block and
  # records the amount of time spent in the block as an interval marker.
  #
  # pkg:gem/vernier#lib/vernier/collector.rb:178
  def record_interval(category, name = T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/collector.rb:139
  def stack_table; end

  # pkg:gem/vernier#lib/vernier/collector.rb:191
  def stop; end

  private

  # pkg:gem/vernier#lib/vernier/collector.rb:141
  def add_hook(hook); end

  class << self
    # pkg:gem/vernier#lib/vernier/collector.rb:99
    def new(mode, options = T.unsafe(nil)); end
  end
end

# pkg:gem/vernier#lib/vernier/collector.rb:8
class Vernier::Collector::CustomCollector < ::Vernier::Collector
  # pkg:gem/vernier#lib/vernier/collector.rb:9
  def initialize(mode, options); end

  # pkg:gem/vernier#lib/vernier/collector.rb:27
  def finish; end

  # pkg:gem/vernier#lib/vernier/collector.rb:19
  def sample; end

  # pkg:gem/vernier#lib/vernier/collector.rb:24
  def start; end
end

# pkg:gem/vernier#lib/vernier/collector.rb:48
class Vernier::Collector::RetainedCollector < ::Vernier::Collector
  # pkg:gem/vernier#lib/vernier/collector.rb:49
  def initialize(mode, options); end

  # pkg:gem/vernier#lib/vernier/collector.rb:61
  def drain; end

  # pkg:gem/vernier#lib/vernier/collector.rb:65
  def finish; end

  # pkg:gem/vernier#lib/vernier/collector.rb:57
  def start; end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::Collector::TimeCollector < ::Vernier::Collector
  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def start; end

  private

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def finish; end

  class << self
    # pkg:gem/vernier#lib/vernier/marker.rb:3
    def new(_arg0, _arg1); end
  end
end

# pkg:gem/vernier#lib/vernier.rb:20
class Vernier::Error < ::StandardError; end

# Plan: The heap tracker can be in a few states:
#  * Idle
#  * Collecting
#    * Watching for new objects
#    * Watching for freed objects
#  * Draining
#    * Ignoring new objects
#    * Watching for freed objects
#  * Locked
#    * Ignoring new objects
#    * Ignoring freed objects
#    * Marking all existing objects (not yet implemented)
#    * N.B. This prevents any objects which the tracker has seen from being GC'd
#
# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::HeapTracker
  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def allocated_objects; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def collect; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def data; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def drain; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def freed_objects; end

  # pkg:gem/vernier#lib/vernier/heap_tracker.rb:24
  def inspect; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def lock; end

  # pkg:gem/vernier#lib/vernier/heap_tracker.rb:41
  def stack(obj); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stack_idx(_arg0); end

  # pkg:gem/vernier#lib/vernier/heap_tracker.rb:18
  def stack_table; end

  # pkg:gem/vernier#lib/vernier/heap_tracker.rb:34
  def track; end

  class << self
    # pkg:gem/vernier#lib/vernier/marker.rb:3
    def _new(_arg0); end

    # pkg:gem/vernier#lib/vernier/heap_tracker.rb:20
    def new(stack_table = T.unsafe(nil)); end

    # pkg:gem/vernier#lib/vernier/heap_tracker.rb:28
    def track(&block); end
  end
end

# pkg:gem/vernier#lib/vernier/hooks.rb:4
module Vernier::Hooks; end

# pkg:gem/vernier#lib/vernier/hooks/active_support.rb:5
class Vernier::Hooks::ActiveSupport
  # pkg:gem/vernier#lib/vernier/hooks/active_support.rb:155
  def initialize(collector); end

  # pkg:gem/vernier#lib/vernier/hooks/active_support.rb:182
  def disable; end

  # pkg:gem/vernier#lib/vernier/hooks/active_support.rb:159
  def enable; end

  # pkg:gem/vernier#lib/vernier/hooks/active_support.rb:187
  def firefox_marker_schema; end
end

# pkg:gem/vernier#lib/vernier/hooks/active_support.rb:6
Vernier::Hooks::ActiveSupport::FIREFOX_MARKER_SCHEMA = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/hooks/active_support.rb:148
Vernier::Hooks::ActiveSupport::SERIALIZED_KEYS = T.let(T.unsafe(nil), Hash)

# pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:5
class Vernier::Hooks::MemoryUsage
  # pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:6
  def initialize(collector); end

  # pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:15
  def disable; end

  # pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:11
  def enable; end

  # pkg:gem/vernier#lib/vernier/hooks/memory_usage.rb:19
  def firefox_counters; end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
module Vernier::Marker
  class << self
    # Return an array of marker names.  The index of the string maps to the
    # value of the corresponding constant
    #
    # pkg:gem/vernier#lib/vernier/marker.rb:36
    def name_table; end
  end
end

# pkg:gem/vernier#lib/vernier/marker.rb:13
Vernier::Marker::MARKER_STRINGS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/marker.rb:7
Vernier::Marker::MARKER_SYMBOLS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/marker.rb:3
module Vernier::Marker::Phase; end

Vernier::Marker::Phase::INSTANT = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Phase::INTERVAL = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Phase::INTERVAL_END = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Phase::INTERVAL_START = T.let(T.unsafe(nil), Integer)

# pkg:gem/vernier#lib/vernier/marker.rb:3
module Vernier::Marker::Type; end

Vernier::Marker::Type::FIBER_SWITCH = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_END_MARK = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_END_SWEEP = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_ENTER = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_EXIT = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_PAUSE = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GC_START = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GVL_THREAD_EXITED = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::GVL_THREAD_STARTED = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::THREAD_RUNNING = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::THREAD_STALLED = T.let(T.unsafe(nil), Integer)
Vernier::Marker::Type::THREAD_SUSPENDED = T.let(T.unsafe(nil), Integer)

# pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:4
class Vernier::MemoryLeakDetector
  # pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:11
  def initialize(collect_time:, idle_time: T.unsafe(nil), drain_time: T.unsafe(nil), **collector_options); end

  # pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:36
  def result; end

  # pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:19
  def start_thread; end

  class << self
    # pkg:gem/vernier#lib/vernier/memory_leak_detector.rb:5
    def start_thread(*, **, &); end
  end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::MemoryTracker
  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def record; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def results; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def start; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stop; end
end

# pkg:gem/vernier#lib/vernier/middleware.rb:2
class Vernier::Middleware
  # pkg:gem/vernier#lib/vernier/middleware.rb:8
  def initialize(app, permit: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/middleware.rb:13
  def call(env); end
end

# pkg:gem/vernier#lib/vernier/middleware.rb:3
Vernier::Middleware::HOOKS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/output/filename_filter.rb:4
module Vernier::Output; end

# pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:7
class Vernier::Output::Cpuprofile
  include ::Vernier::OutputHelpers

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:10
  def initialize(profile); end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:14
  def output; end

  private

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:57
  def build_nodes; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:134
  def calculate_time_deltas(timestamps); end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:89
  def create_node_for_stack(stack_idx, nodes, stack_table); end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:26
  def data; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:47
  def empty_profile; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:22
  def ns_to_us(timestamp); end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:20
  def profile; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:74
  def root_node; end

  # pkg:gem/vernier#lib/vernier/output/cpuprofile.rb:130
  def stack_to_node_id(stack_idx); end
end

# pkg:gem/vernier#lib/vernier/output/file_listing.rb:9
class Vernier::Output::FileListing
  include ::Vernier::OutputHelpers

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:19
  def initialize(profile); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:134
  def format_file(output, filename, all_samples, total:); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:163
  def format_file_html(output, filename, relevant_files); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:151
  def html_output(output, relevant_files); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:107
  def output(template: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:23
  def samples_by_file; end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:130
  def total; end

  private

  # Returns [self_weight, total_weight] arrays indexed by frame, from a
  # hash of per-stack weights.
  #
  # The stack table is a prefix tree whose parent is always interned
  # before its children (parent idx < child idx), so total weights are
  # accumulated bottom-up in a single reverse pass.
  #
  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:73
  def frame_weights(stack_table, stack_weights); end
end

# pkg:gem/vernier#lib/vernier/output/file_listing.rb:12
class Vernier::Output::FileListing::SamplesByLocation
  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:14
  def initialize; end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:13
  def self; end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:13
  def self=(_arg0); end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:13
  def total; end

  # pkg:gem/vernier#lib/vernier/output/file_listing.rb:13
  def total=(_arg0); end
end

# pkg:gem/vernier#lib/vernier/output/filename_filter.rb:5
class Vernier::Output::FilenameFilter
  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:6
  def initialize; end

  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:15
  def call(filename); end

  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:13
  def gem_match_regex; end

  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:13
  def gem_regex; end

  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:13
  def pwd; end

  # pkg:gem/vernier#lib/vernier/output/filename_filter.rb:13
  def rubylibdir; end
end

# https://profiler.firefox.com/
# https://github.com/firefox-devtools/profiler/blob/main/src/types/profile.ts
#
# pkg:gem/vernier#lib/vernier/output/firefox.rb:13
class Vernier::Output::Firefox
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:118
  def initialize(profile); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:123
  def output(gzip: T.unsafe(nil)); end

  private

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:195
  def counter_data; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:136
  def data; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:203
  def marker_schema; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:134
  def profile; end
end

# pkg:gem/vernier#lib/vernier/output/firefox.rb:14
class Vernier::Output::Firefox::Categorizer
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:26
  def initialize; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:70
  def add_category(name:, **kw); end

  # This is in the order of preference
  #
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:24
  def categories; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:91
  def categorize(path); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:87
  def gem_path(*names); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:79
  def get_category(name); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:83
  def starts_with(*paths); end
end

# pkg:gem/vernier#lib/vernier/output/firefox.rb:19
Vernier::Output::Firefox::Categorizer::AVAILABLE_COLORS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/output/firefox.rb:95
class Vernier::Output::Firefox::Categorizer::Category
  # pkg:gem/vernier#lib/vernier/output/firefox.rb:98
  def initialize(idx, name:, color:, matcher: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:108
  def add_subcategory(**args); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:96
  def color; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:96
  def idx; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:96
  def matcher; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:112
  def matches?(path); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:96
  def name; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:96
  def subcategories; end
end

# pkg:gem/vernier#lib/vernier/output/firefox.rb:22
Vernier::Output::Firefox::Categorizer::ORDERED_CATEGORIES = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/output/firefox.rb:15
Vernier::Output::Firefox::Categorizer::RAILS_COMPONENTS = T.let(T.unsafe(nil), Array)

# pkg:gem/vernier#lib/vernier/output/firefox.rb:270
class Vernier::Output::Firefox::Thread
  include ::Vernier::OutputHelpers

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:280
  def initialize(ruby_thread_id, profile, categorizer, name:, tid:, samples:, weights:, markers:, started_at:, timestamps: T.unsafe(nil), sample_categories: T.unsafe(nil), stopped_at: T.unsafe(nil), allocations: T.unsafe(nil), is_main: T.unsafe(nil), is_start: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:498
  def allocations_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:393
  def categorize_filename(filename); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:402
  def cfunc_category_and_subcategory; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:426
  def data; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:419
  def filter_filenames(filenames); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:410
  def find_category_and_subcategory(filename, categories); end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:580
  def frame_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:617
  def func_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:278
  def is_start; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:458
  def markers_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:278
  def profile; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:406
  def ruby_category_and_subcategory; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:518
  def samples_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:554
  def stack_table; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:642
  def string_table; end

  private

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:650
  def gc_category; end

  # pkg:gem/vernier#lib/vernier/output/firefox.rb:654
  def thread_category; end
end

# pkg:gem/vernier#lib/vernier/output/firefox.rb:273
Vernier::Output::Firefox::Thread::SAMPLE_CATEGORY_NAMES = T.let(T.unsafe(nil), Hash)

# pkg:gem/vernier#lib/vernier/output/markdown.rb:7
class Vernier::Output::Markdown
  # pkg:gem/vernier#lib/vernier/output/markdown.rb:11
  def initialize(profile, top_n: T.unsafe(nil), lines_per_file: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:17
  def output; end

  private

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:185
  def build_files; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:79
  def build_hotspots; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:33
  def build_summary; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:156
  def build_threads; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:29
  def build_title; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:406
  def escape_markdown(text); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:339
  def filter_filename(filename); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:392
  def format_code_span(text); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:353
  def format_location(file, line); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:293
  def get_stack_table(thread); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:309
  def get_thread_main(thread); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:301
  def get_thread_name(thread); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:317
  def get_thread_tid(thread); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:277
  def get_threads; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:348
  def live_profile?; end

  # Helper methods
  #
  # pkg:gem/vernier#lib/vernier/output/markdown.rb:273
  def main_thread; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:359
  def read_source_line(filename, line_no); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:372
  def resolve_filename(filename); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:334
  def thread_count; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:134
  def top_functions_table(title, funcs, total, sort_key); end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:325
  def total_samples; end

  # pkg:gem/vernier#lib/vernier/output/markdown.rb:383
  def truncate_code(code, max_length: T.unsafe(nil)); end
end

# pkg:gem/vernier#lib/vernier/output/markdown.rb:9
Vernier::Output::Markdown::DEFAULT_LINES_PER_FILE = T.let(T.unsafe(nil), Integer)

# pkg:gem/vernier#lib/vernier/output/markdown.rb:8
Vernier::Output::Markdown::DEFAULT_TOP_N = T.let(T.unsafe(nil), Integer)

# pkg:gem/vernier#lib/vernier/output/top.rb:7
class Vernier::Output::Top
  include ::Vernier::OutputHelpers

  # pkg:gem/vernier#lib/vernier/output/top.rb:10
  def initialize(profile, row_limit); end

  # pkg:gem/vernier#lib/vernier/output/top.rb:55
  def output; end
end

# pkg:gem/vernier#lib/vernier/output/top.rb:15
class Vernier::Output::Top::Table
  # pkg:gem/vernier#lib/vernier/output/top.rb:16
  def initialize(header, row_limit); end

  # pkg:gem/vernier#lib/vernier/output/top.rb:23
  def <<(row); end

  # pkg:gem/vernier#lib/vernier/output/top.rb:50
  def format_row(row); end

  # pkg:gem/vernier#lib/vernier/output/top.rb:46
  def row_separator; end

  # pkg:gem/vernier#lib/vernier/output/top.rb:27
  def to_s; end

  # pkg:gem/vernier#lib/vernier/output/top.rb:39
  def widths; end
end

# pkg:gem/vernier#lib/vernier/output_helpers.rb:4
module Vernier::OutputHelpers
  # Collapses parallel samples/weights arrays into a hash of total weight
  # per stack index. Retained-mode profiles have one sample per object and
  # many samples share the same stack, so collapsing first keeps later
  # aggregation proportional to the number of unique stacks.
  #
  # pkg:gem/vernier#lib/vernier/output_helpers.rb:9
  def collapse_stack_weights(samples, weights); end

  # Returns a string safe to embed in JSON output: valid UTF-8 with any
  # invalid bytes replaced. Method names and paths can carry arbitrary
  # encodings (e.g. BINARY or Shift_JIS source), which would otherwise
  # raise JSON::GeneratorError.
  #
  # pkg:gem/vernier#lib/vernier/output_helpers.rb:21
  def sanitize_string(string); end
end

# pkg:gem/vernier#lib/vernier/parsed_profile.rb:7
class Vernier::ParsedProfile
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:87
  def initialize(data); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:86
  def data; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:98
  def main_thread; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:91
  def threads; end

  class << self
    # pkg:gem/vernier#lib/vernier/parsed_profile.rb:8
    def read_file(filename); end
  end
end

# pkg:gem/vernier#lib/vernier/parsed_profile.rb:24
class Vernier::ParsedProfile::StackTable
  include ::Vernier::StackTableHelpers

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:25
  def initialize(thread_data); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:39
  def frame_count; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:45
  def frame_func_idx(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:46
  def frame_line_no(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:40
  def func_count; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:51
  def func_filename(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:49
  def func_filename_idx(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:52
  def func_first_lineno(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:50
  def func_name(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:48
  def func_name_idx(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:38
  def stack_count; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:43
  def stack_frame_idx(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:42
  def stack_parent_idx(idx); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:36
  def strings; end
end

# pkg:gem/vernier#lib/vernier/parsed_profile.rb:57
class Vernier::ParsedProfile::Thread
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:60
  def initialize(data); end

  # Emulate hash
  #
  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:81
  def [](name); end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:58
  def data; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:68
  def main_thread?; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:72
  def samples; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:64
  def stack_table; end

  # pkg:gem/vernier#lib/vernier/parsed_profile.rb:76
  def weights; end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::Result
  # pkg:gem/vernier#lib/vernier/result.rb:6
  def _stack_table; end

  # pkg:gem/vernier#lib/vernier/result.rb:70
  def each_sample; end

  # pkg:gem/vernier#lib/vernier/result.rb:62
  def elapsed_seconds; end

  # pkg:gem/vernier#lib/vernier/result.rb:8
  def end_time; end

  # pkg:gem/vernier#lib/vernier/result.rb:8
  def end_time=(_arg0); end

  # pkg:gem/vernier#lib/vernier/result.rb:10
  def gc_markers; end

  # pkg:gem/vernier#lib/vernier/result.rb:8
  def hooks; end

  # pkg:gem/vernier#lib/vernier/result.rb:8
  def hooks=(_arg0); end

  # pkg:gem/vernier#lib/vernier/result.rb:66
  def inspect; end

  # pkg:gem/vernier#lib/vernier/result.rb:12
  def main_thread; end

  # pkg:gem/vernier#lib/vernier/result.rb:10
  def meta; end

  # pkg:gem/vernier#lib/vernier/result.rb:8
  def pid; end

  # pkg:gem/vernier#lib/vernier/result.rb:8
  def pid=(_arg0); end

  # pkg:gem/vernier#lib/vernier/result.rb:79
  def stack(idx); end

  # pkg:gem/vernier#lib/vernier/result.rb:5
  def stack_table; end

  # pkg:gem/vernier#lib/vernier/result.rb:5
  def stack_table=(_arg0); end

  # Realtime in nanoseconds since the unix epoch
  #
  # pkg:gem/vernier#lib/vernier/result.rb:17
  def started_at; end

  # pkg:gem/vernier#lib/vernier/result.rb:10
  def threads; end

  # pkg:gem/vernier#lib/vernier/result.rb:29
  def to_cpuprofile; end

  # pkg:gem/vernier#lib/vernier/result.rb:24
  def to_firefox(gzip: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/result.rb:27
  def to_gecko(gzip: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/result.rb:33
  def to_markdown(top_n: T.unsafe(nil), lines_per_file: T.unsafe(nil)); end

  # pkg:gem/vernier#lib/vernier/result.rb:87
  def total_bytes; end

  # pkg:gem/vernier#lib/vernier/result.rb:95
  def total_samples; end

  # pkg:gem/vernier#lib/vernier/result.rb:99
  def total_unique_samples; end

  # pkg:gem/vernier#lib/vernier/result.rb:83
  def total_weights; end

  # pkg:gem/vernier#lib/vernier/result.rb:37
  def write(out:, format: T.unsafe(nil)); end
end

# pkg:gem/vernier#lib/vernier/marker.rb:3
class Vernier::StackTable
  include ::Vernier::StackTableHelpers

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def convert(_arg0, _arg1); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def current_stack(*_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def finalize; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def frame_count; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def frame_func_idx(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def frame_line_no(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_absolute_path(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_count; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_filename(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_first_lineno(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_name(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def func_path(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stack_count; end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stack_frame_idx(_arg0); end

  # pkg:gem/vernier#lib/vernier/marker.rb:3
  def stack_parent_idx(_arg0); end

  class << self
    # pkg:gem/vernier#lib/vernier/marker.rb:3
    def new; end
  end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:2
module Vernier::StackTableHelpers
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:25
  def backtrace(stack_idx); end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:43
  def full_stack(stack_idx); end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:3
  def inspect; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:149
  def stack(idx); end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:7
  def to_h; end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:52
class Vernier::StackTableHelpers::BaseType
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:54
  def initialize(stack_table, idx); end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:53
  def idx; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:59
  def inspect; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:53
  def stack_table; end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:79
class Vernier::StackTableHelpers::Frame < ::Vernier::StackTableHelpers::BaseType
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:81
  def filename; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:84
  def func; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:80
  def label; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:89
  def line; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:92
  def lineno; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:82
  def name; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:94
  def to_s; end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:64
class Vernier::StackTableHelpers::Func < ::Vernier::StackTableHelpers::BaseType
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:70
  def filename; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:65
  def label; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:68
  def name; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:74
  def to_s; end
end

# pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:103
class Vernier::StackTableHelpers::Stack < ::Vernier::StackTableHelpers::BaseType
  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:116
  def [](offset); end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:104
  def each; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:114
  def each_frame; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:136
  def frames; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:132
  def leaf_frame; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:128
  def leaf_frame_idx; end

  # pkg:gem/vernier#lib/vernier/stack_table_helpers.rb:140
  def to_s; end
end

# Collects names of all seen threads
#
# pkg:gem/vernier#lib/vernier/thread_names.rb:3
class Vernier::ThreadNames
  # pkg:gem/vernier#lib/vernier/thread_names.rb:4
  def initialize; end

  # pkg:gem/vernier#lib/vernier/thread_names.rb:12
  def [](object_id); end

  # pkg:gem/vernier#lib/vernier/thread_names.rb:16
  def finish; end

  private

  # pkg:gem/vernier#lib/vernier/thread_names.rb:23
  def collect_running; end

  # pkg:gem/vernier#lib/vernier/thread_names.rb:29
  def collect_thread(th); end

  # pkg:gem/vernier#lib/vernier/thread_names.rb:33
  def pretty_name(thread); end
end

# pkg:gem/vernier#lib/vernier/version.rb:4
Vernier::VERSION = T.let(T.unsafe(nil), String)
