AllCops:
  TargetRubyVersion: 2.7

require:
  - standard
  - standard-custom
  - standard-performance

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
