inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude
    - Include

inherit_gem:
  rubocop-gusto:
    - config/default.yml
    - config/sidekiq.yml

plugins:
  - rubocop-gusto
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - 'vendor/**/*'
