name: CI Test
on: [ push ]
jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.2
          - 3.3
          - 3.4
          - 4.0
    env:
      CI: 1
      USE_OFFICIAL_GEM_SOURCE: 1
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
      - run: bundle exec rspec
