name: RuboCop

on: [push, pull_request]

permissions:
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@e8944e80fb94b20106697132f8c20c665fab29e9 # v1.325.0
        with:
          bundler-cache: true
          ruby-version: "3.4"
      - name: Run RuboCop
        run: bundle exec rubocop
